/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DreamAnalyzerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  openaiApiKey: "",
  openaiModel: "gpt-5-mini",
  embeddingModel: "text-embedding-3-small",
  dreamsFolder: "Dreams",
  templateFilePath: "Templates/Dream Template.md",
  similarityThreshold: 0.35,
  similarityLimit: 40,
  autoUpdateEmbeddings: true
};
var ENTITY_TYPES = [
  { field: "characters", folder: "\u041F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0456", entity_type: "character" },
  { field: "places", folder: "\u041C\u0456\u0441\u0446\u044F", entity_type: "place" },
  { field: "objects", folder: "\u041F\u0440\u0435\u0434\u043C\u0435\u0442\u0438", entity_type: "object" },
  { field: "symbols", folder: "\u0421\u0438\u043C\u0432\u043E\u043B\u0438", entity_type: "symbol" },
  { field: "emotions", folder: "\u0415\u043C\u043E\u0446\u0456\u0457", entity_type: "emotion" },
  { field: "concepts", folder: "\u041A\u043E\u043D\u0446\u0435\u043F\u0442\u0438", entity_type: "concept" }
];

// src/settings.ts
var import_obsidian7 = require("obsidian");

// src/embeddings.ts
var import_obsidian3 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");
async function getOpenAiApiKey(app, settings) {
  if (settings.openaiApiKey && settings.openaiApiKey.trim().length > 0) {
    return settings.openaiApiKey.trim();
  }
  throw new Error(`OpenAI API key \u043D\u0435 \u0432\u043A\u0430\u0437\u0430\u043D\u043E! \u0411\u0443\u0434\u044C \u043B\u0430\u0441\u043A\u0430, \u0432\u043A\u0430\u0436\u0456\u0442\u044C API \u043A\u043B\u044E\u0447 \u0443 \u043D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F\u0445 \u043F\u043B\u0430\u0433\u0456\u043D\u0430 "Dream Analyzer".`);
}
async function getEmbedding(apiKey, model, input) {
  const batch = await getBatchEmbeddings(apiKey, model, [input]);
  if (!batch || batch.length === 0) {
    throw new Error("\u041F\u0430\u043A\u0435\u0442\u0438 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432 \u043F\u043E\u0432\u0435\u0440\u043D\u0443\u043B\u0438 \u043F\u043E\u0440\u043E\u0436\u043D\u0456\u0439 \u043C\u0430\u0441\u0438\u0432");
  }
  return batch[0];
}
async function getBatchEmbeddings(apiKey, model, inputs) {
  if (!inputs || inputs.length === 0) return [];
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.openai.com/v1/embeddings",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: model || "text-embedding-3-small",
        input: inputs
      })
    });
    if (response.status !== 200) {
      let errorDetail = response.text;
      try {
        const errJson = JSON.parse(response.text);
        if (errJson?.error?.message) {
          errorDetail = errJson.error.message;
        }
      } catch (e) {
      }
      throw new Error(`OpenAI API Error ${response.status}: ${errorDetail}`);
    }
    const data = JSON.parse(response.text);
    if (!data.data || !Array.isArray(data.data)) {
      throw new Error("\u041D\u0435\u043A\u043E\u0440\u0435\u043A\u0442\u043D\u0438\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 \u0432\u0456\u0434\u043F\u043E\u0432\u0456\u0434\u0456 embeddings \u0432\u0456\u0434 OpenAI");
    }
    const sorted = data.data.sort((a, b) => a.index - b.index);
    return sorted.map((item) => item.embedding);
  } catch (error) {
    console.error("Dream Analyzer Batch Embedding Error:", error);
    throw new Error(`\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u0457 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432: ${error.message || error}`);
  }
}
async function requestChatCompletion(apiKey, model, systemPrompt, userPrompt) {
  try {
    const selectedModel = model || "gpt-4o-mini";
    const payload = {
      model: selectedModel,
      messages: [
        {
          role: "system",
          content: systemPrompt
        },
        {
          role: "user",
          content: userPrompt
        }
      ],
      response_format: { type: "json_object" }
    };
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.openai.com/v1/chat/completions",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    });
    if (response.status !== 200) {
      let errorDetail = response.text;
      try {
        const errJson = JSON.parse(response.text);
        if (errJson?.error?.message) {
          errorDetail = errJson.error.message;
        }
      } catch (e) {
      }
      throw new Error(`OpenAI API Error ${response.status}: ${errorDetail}`);
    }
    const data = JSON.parse(response.text);
    if (!data.choices || !data.choices[0] || !data.choices[0].message) {
      throw new Error("\u041D\u0435\u043A\u043E\u0440\u0435\u043A\u0442\u043D\u0430 \u0432\u0456\u0434\u043F\u043E\u0432\u0456\u0434\u044C ChatCompletion \u0432\u0456\u0434 OpenAI");
    }
    return JSON.parse(data.choices[0].message.content);
  } catch (error) {
    console.error("Dream Analyzer ChatCompletion Error:", error);
    throw new Error(`\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0437\u0430\u043F\u0438\u0442\u0443 \u0434\u043E OpenAI: ${error.message || error}`);
  }
}

// src/i18n.ts
var import_obsidian2 = require("obsidian");
function getLocale() {
  try {
    const obsLang = (window.localStorage.getItem("language") || "").toLowerCase();
    if (obsLang) {
      if (obsLang.startsWith("uk") || obsLang.startsWith("ua")) {
        return "uk";
      }
      return "en";
    }
    const momentLang = (import_obsidian2.moment.locale() || "").toLowerCase();
    if (momentLang.startsWith("uk") || momentLang.startsWith("ua")) {
      return "uk";
    }
  } catch (e) {
  }
  return "en";
}
var strings = {
  uk: {
    // Dashboard
    dashboardFileName: "\u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u0456\u0432.md",
    dashboardTitle: "# \u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u044C \u0442\u0430 \u0430\u043D\u0430\u043B\u0456\u0442\u0438\u043A\u0438",
    dashboardCallout: "> [!INFO] \u0410\u043D\u0430\u043B\u0456\u0442\u0438\u043A\u0430 \u0442\u0430 \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430\n> \u0426\u0435\u0439 \u0434\u0430\u0448\u0431\u043E\u0440\u0434 \u0430\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u043D\u043E \u0441\u0442\u0432\u043E\u0440\u0435\u043D\u043E \u043F\u043B\u0430\u0433\u0456\u043D\u043E\u043C **Dream Analyzer**. \u0412\u0456\u043D \u043C\u0456\u0441\u0442\u0438\u0442\u044C \u043A\u043B\u044E\u0447\u043E\u0432\u0456 Dataview-\u0437\u0430\u043F\u0438\u0442\u0438 \u0434\u043B\u044F \u0432\u0456\u0434\u0441\u0442\u0435\u0436\u0435\u043D\u043D\u044F \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0438 \u0441\u043D\u0456\u0432, \u043C\u0430\u0440\u043A\u0435\u0440\u0456\u0432 \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043E\u0441\u0442\u0456 (Dream Signs), \u0435\u043C\u043E\u0446\u0456\u0439\u043D\u043E\u0433\u043E \u0444\u043E\u043D\u0443 \u0442\u0430 \u0456\u0434\u0435\u0439 \u0434\u043B\u044F \u0442\u0432\u043E\u0440\u0447\u043E\u0441\u0442\u0456.",
    dashboardSectionStats: "## \u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430 \u0442\u0430 \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043E\u0441\u0442\u0456 (\u041E\u0421)",
    dashboardSectionSigns: "## \u041C\u0430\u0440\u043A\u0435\u0440\u0438 \u0441\u043D\u0456\u0432 \u0434\u043B\u044F \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043D\u044F (Dream Signs)\n*\u041D\u0430\u0439\u0447\u0430\u0441\u0442\u0456\u0448\u0456 \u0441\u0438\u043C\u0432\u043E\u043B\u0438, \u043F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0456 \u0442\u0430 \u043C\u0456\u0441\u0446\u044F \u2014 \u0432\u0430\u0448\u0456 \u0442\u0440\u0438\u0433\u0435\u0440\u0438 \u0434\u043B\u044F \u043F\u0435\u0440\u0435\u0432\u0456\u0440\u043A\u0438 \u0440\u0435\u0430\u043B\u044C\u043D\u043E\u0441\u0442\u0456 \u0443 \u0441\u043D\u0456.*",
    dashboardSectionEmotions: "## \u0415\u043C\u043E\u0446\u0456\u0439\u043D\u0438\u0439 \u0444\u043E\u043D \u0442\u0430 \u043F\u0441\u0438\u0445\u043E\u043B\u043E\u0433\u0456\u0447\u043D\u0456 \u0441\u0442\u0430\u043D\u0438\n*\u0415\u043C\u043E\u0446\u0456\u0457 \u0442\u0430 \u0432\u043D\u0443\u0442\u0440\u0456\u0448\u043D\u0456 \u0441\u0442\u0430\u043D\u0438, \u044F\u043A\u0456 \u043D\u0430\u0439\u0447\u0430\u0441\u0442\u0456\u0448\u0435 \u0432\u0438\u043D\u0438\u043A\u0430\u044E\u0442\u044C \u0443 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F\u0445.*",
    dashboardSectionCreative: "## \u0421\u0432\u0456\u0442 \u0441\u043D\u0456\u0432: \u041A\u043E\u043D\u0446\u0435\u043F\u0442\u0438 & \u0406\u0434\u0435\u0457 \u0434\u043B\u044F \u0442\u0432\u043E\u0440\u0447\u043E\u0441\u0442\u0456 \u0442\u0430 \u043A\u043D\u0438\u0433\n*\u0410\u0431\u0441\u0442\u0440\u0430\u043A\u0442\u043D\u0456 \u0456\u0434\u0435\u0457, \u0443\u043D\u0456\u043A\u0430\u043B\u044C\u043D\u0456 \u043B\u043E\u043A\u0430\u0446\u0456\u0457 \u0442\u0430 \u044F\u0441\u043A\u0440\u0430\u0432\u0456 \u043F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0456 \u0437 \u043E\u043F\u0438\u0441\u043E\u043C.*",
    dashboardSectionLucid: "## \u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0456 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F (\u041E\u0421)\n*\u0416\u0443\u0440\u043D\u0430\u043B \u0432\u0430\u0448\u0438\u0445 \u0443\u0441\u043F\u0456\u0448\u043D\u0438\u0445 \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u0445 \u0441\u043D\u0456\u0432.*",
    dashboardSectionRecent: "## \u041E\u0441\u0442\u0430\u043D\u043D\u0456 \u0437\u0430\u043F\u0438\u0441\u0438 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430",
    // Ribbon & Commands
    ribbonAnalyze: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u0432\u0430\u0442\u0438 \u0441\u043E\u043D (Dream Analyzer)",
    ribbonCreateDream: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 \u0441\u043E\u043D \u043D\u0430 \u0441\u044C\u043E\u0433\u043E\u0434\u043D\u0456",
    cmdAnalyze: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u0432\u0430\u0442\u0438 \u0430\u043A\u0442\u0438\u0432\u043D\u0438\u0439 \u0441\u043E\u043D",
    cmdCreateDream: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 \u0441\u043E\u043D \u043D\u0430 \u0441\u044C\u043E\u0433\u043E\u0434\u043D\u0456",
    cmdCreateCustomDateDream: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 \u0441\u043E\u043D \u0437\u0430 \u043E\u0431\u0440\u0430\u043D\u0443 \u0434\u0430\u0442\u0443...",
    cmdRebuildEmbeddings: "\u041E\u043D\u043E\u0432\u0438\u0442\u0438 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439",
    cmdResetAllData: "\u0421\u043A\u0438\u043D\u0443\u0442\u0438 \u0432\u0441\u0456 \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u0456 \u0434\u0430\u043D\u0456 \u0442\u0430 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456...",
    contextMenuAnalyze: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u0432\u0430\u0442\u0438 \u0441\u043E\u043D",
    // Date Modal
    dateModalTitle: "\u041E\u0431\u0435\u0440\u0456\u0442\u044C \u0434\u0430\u0442\u0443 \u0441\u043D\u0443",
    dateModalLabel: "\u0414\u0430\u0442\u0430 \u0441\u043D\u0443",
    dateModalButton: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 / \u0412\u0456\u0434\u043A\u0440\u0438\u0442\u0438 \u0441\u043E\u043D",
    // Reset Modal & Settings
    resetModalTitle: "\u041E\u0447\u0438\u0449\u0435\u043D\u043D\u044F \u0432\u0441\u0456\u0445 \u0437\u043D\u0430\u0439\u0434\u0435\u043D\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u043E\u0457 \u0431\u0430\u0437\u0438",
    resetModalDesc: "\u0426\u0435 \u0432\u0438\u0434\u0430\u043B\u0438\u0442\u044C \u0443\u0441\u0456 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439, \u043E\u0431\u043D\u0443\u043B\u0438\u0442\u044C \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0456 \u0431\u0430\u0437\u0438 (embeddings.json) \u0442\u0430 \u0441\u043A\u0438\u043D\u0435 \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u0438\u0439 AI-\u0432\u043C\u0456\u0441\u0442 \u0443\u0441\u0456\u0445 \u0441\u043D\u0456\u0432 \u0434\u043E \u043F\u043E\u0447\u0430\u0442\u043A\u043E\u0432\u043E\u0433\u043E \u0441\u0442\u0430\u043D\u0443. \u0422\u0435\u043A\u0441\u0442\u0438 \u0441\u0430\u043C\u0438\u0445 \u0441\u043D\u0456\u0432 \u0437\u0430\u043B\u0438\u0448\u0430\u0442\u044C\u0441\u044F \u043D\u0435\u0434\u043E\u0442\u043E\u0440\u043A\u0430\u043D\u0438\u043C\u0438.",
    resetModalConfirmButton: "\u0421\u043A\u0438\u043D\u0443\u0442\u0438 \u0432\u0441\u0435",
    resetModalCancelButton: "\u0421\u043A\u0430\u0441\u0443\u0432\u0430\u0442\u0438",
    resetSuccess: "\u0421\u043A\u0438\u043D\u0443\u0442\u043E \u0441\u043D\u0456\u0432: {dreams}, \u0432\u0438\u0434\u0430\u043B\u0435\u043D\u043E \u0444\u0430\u0439\u043B\u0456\u0432 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439: {entities}.",
    resetSectionTitle: "\u0421\u043A\u0438\u043D\u0443\u0442\u0438 \u0442\u0430 \u043E\u0447\u0438\u0441\u0442\u0438\u0442\u0438 \u0434\u0430\u043D\u0456",
    resetSectionDesc: "\u0412\u0438\u0434\u0430\u043B\u0438\u0442\u0438 \u0432\u0441\u0456 \u0437\u0433\u0435\u043D\u0435\u0440\u043E\u0432\u0430\u043D\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456 \u0442\u0430 \u0441\u043A\u0438\u043D\u0443\u0442\u0438 \u0441\u043D\u0438 \u0434\u043E \u043F\u043E\u0447\u0430\u0442\u043A\u043E\u0432\u043E\u0433\u043E \u0441\u0442\u0430\u043D\u0443 \u0434\u043B\u044F \u043F\u043E\u0432\u0442\u043E\u0440\u043D\u043E\u0433\u043E \u0430\u043D\u0430\u043B\u0456\u0437\u0443",
    resetButtonText: "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u0438 \u0432\u0441\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456 \u0442\u0430 \u0430\u043D\u0430\u043B\u0456\u0437",
    // Templater Exporter
    templateExportSuccess: "\u0428\u0430\u0431\u043B\u043E\u043D \u0434\u043B\u044F Templater / Calendar \u0443\u0441\u043F\u0456\u0448\u043D\u043E \u0437\u0431\u0435\u0440\u0435\u0436\u0435\u043D\u043E \u0443 {path}!",
    templateExportName: "\u0428\u0430\u0431\u043B\u043E\u043D \u0434\u043B\u044F Templater & Calendar",
    templateExportDesc: "\u0417\u0431\u0435\u0440\u0435\u0433\u0442\u0438 \u0441\u0443\u043C\u0456\u0441\u043D\u0438\u0439 \u0448\u0430\u0431\u043B\u043E\u043D \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u043D\u0443 \u0443 Vault \u0434\u043B\u044F \u043F\u043B\u0430\u0433\u0456\u043D\u0456\u0432 Templater \u0442\u0430 Calendar",
    templatePathName: "\u0428\u043B\u044F\u0445 \u0434\u043E \u0444\u0430\u0439\u043B\u0443 \u0448\u0430\u0431\u043B\u043E\u043D\u0443",
    templatePathDesc: "\u0424\u0430\u0439\u043B \u0443 \u0441\u0445\u043E\u0432\u0438\u0449\u0456, \u043A\u0443\u0434\u0438 \u0431\u0443\u0434\u0435 \u0437\u0430\u043F\u0438\u0441\u0430\u043D\u043E \u0448\u0430\u0431\u043B\u043E\u043D (\u043D\u0430\u043F\u0440\u0438\u043A\u043B\u0430\u0434, Templates/Dream Template.md)",
    templateExportButtonText: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 / \u043E\u043D\u043E\u0432\u0438\u0442\u0438 \u0444\u0430\u0439\u043B \u0448\u0430\u0431\u043B\u043E\u043D\u0443",
    // Notices
    noActiveNote: "\u041D\u0435\u043C\u0430\u0454 \u0432\u0456\u0434\u043A\u0440\u0438\u0442\u043E\u0457 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u043D\u0443",
    openDreamNoteFirst: "\u0411\u0443\u0434\u044C \u043B\u0430\u0441\u043A\u0430, \u0432\u0456\u0434\u043A\u0440\u0438\u0439\u0442\u0435 \u043D\u043E\u0442\u0430\u0442\u043A\u0443 \u0441\u043D\u0443 \u0434\u043B\u044F \u0430\u043D\u0430\u043B\u0456\u0437\u0443.",
    noApiKey: "OpenAI API key \u043D\u0435 \u0432\u043A\u0430\u0437\u0430\u043D\u043E! \u0411\u0443\u0434\u044C \u043B\u0430\u0441\u043A\u0430, \u0432\u043A\u0430\u0436\u0456\u0442\u044C API \u043A\u043B\u044E\u0447 \u0443 \u043D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F\u0445 \u043F\u043B\u0430\u0433\u0456\u043D\u0430 Dream Analyzer.",
    analyzingStep1: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u044E \u0441\u043E\u043D: \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0434\u0430\u043D\u0438\u0445...",
    analyzingStep2: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u044E \u0441\u043E\u043D: \u043F\u043E\u0448\u0443\u043A \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439...",
    analyzingStep3: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u044E \u0441\u043E\u043D: \u0437\u0430\u043F\u0438\u0442 \u0434\u043E OpenAI ({model})...",
    analyzingStep4: "\u0421\u0442\u0432\u043E\u0440\u0435\u043D\u043D\u044F \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u0440\u043E\u0437\u0440\u0430\u0445\u0443\u043D\u043E\u043A \u0437\u0432'\u044F\u0437\u043A\u0456\u0432...",
    analyzingStep5: "\u041F\u0430\u043A\u0435\u0442\u043D\u0435 \u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432...",
    analysisSuccess: "\u0421\u043E\u043D \u0443\u0441\u043F\u0456\u0448\u043D\u043E \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u043E \u0437\u0430 {sec}\u0441!",
    analysisError: "\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443: ",
    rebuildStart: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432...",
    rebuildSuccess: "\u0413\u043E\u0442\u043E\u0432\u043E! \u0417\u0433\u0435\u043D\u0435\u0440\u043E\u0432\u0430\u043D\u043E/\u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043E \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432: {count}",
    dreamAlreadyExists: "\u041D\u043E\u0442\u0430\u0442\u043A\u0430 \u0441\u043D\u0443 \u043D\u0430 \u0446\u044E \u0434\u0430\u0442\u0443 \u0432\u0436\u0435 \u0456\u0441\u043D\u0443\u0454!",
    dreamCreated: "\u0421\u0442\u0432\u043E\u0440\u0435\u043D\u043E \u043D\u043E\u0432\u0443 \u043D\u043E\u0442\u0430\u0442\u043A\u0443 \u0441\u043D\u0443!",
    // Days & Months
    days: ["\u043D\u0435\u0434\u0456\u043B\u044F", "\u043F\u043E\u043D\u0435\u0434\u0456\u043B\u043E\u043A", "\u0432\u0456\u0432\u0442\u043E\u0440\u043E\u043A", "\u0441\u0435\u0440\u0435\u0434\u0430", "\u0447\u0435\u0442\u0432\u0435\u0440", "\u043F'\u044F\u0442\u043D\u0438\u0446\u044F", "\u0441\u0443\u0431\u043E\u0442\u0430"],
    months: [
      "01 - \u0441\u0456\u0447\u0435\u043D\u044C",
      "02 - \u043B\u044E\u0442\u0438\u0439",
      "03 - \u0431\u0435\u0440\u0435\u0437\u0435\u043D\u044C",
      "04 - \u043A\u0432\u0456\u0442\u0435\u043D\u044C",
      "05 - \u0442\u0440\u0430\u0432\u0435\u043D\u044C",
      "06 - \u0447\u0435\u0440\u0432\u0435\u043D\u044C",
      "07 - \u043B\u0438\u043F\u0435\u043D\u044C",
      "08 - \u0441\u0435\u0440\u043F\u0435\u043D\u044C",
      "09 - \u0432\u0435\u0440\u0435\u0441\u0435\u043D\u044C",
      "10 - \u0436\u043E\u0432\u0442\u0435\u043D\u044C",
      "11 - \u043B\u0438\u0441\u0442\u043E\u043F\u0430\u0434",
      "12 - \u0433\u0440\u0443\u0434\u0435\u043D\u044C"
    ],
    // Settings
    settingsTitle: "\u041D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F Dream Analyzer",
    apiKeyName: "OpenAI API Key",
    apiKeyDesc: "\u0412\u0432\u0435\u0434\u0456\u0442\u044C \u0441\u0432\u0456\u0439 \u0441\u0435\u043A\u0440\u0435\u0442\u043D\u0438\u0439 API \u043A\u043B\u044E\u0447 OpenAI (sk-...)",
    modelName: "\u041C\u043E\u0434\u0435\u043B\u044C OpenAI Chat",
    modelDesc: "\u0412\u0438\u0431\u0435\u0440\u0456\u0442\u044C \u043C\u043E\u0434\u0435\u043B\u044C AI \u0434\u043B\u044F \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443",
    gptDefaultLabel: "GPT-5 mini (\u0417\u0430 \u0437\u0430\u043C\u043E\u0432\u0447\u0443\u0432\u0430\u043D\u043D\u044F\u043C)",
    sectionJournalFolder: "\u0421\u0442\u0440\u0443\u043A\u0442\u0443\u0440\u0430 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430 \u0441\u043D\u0456\u0432",
    sectionVectorSearch: "\u0412\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0439 \u043F\u043E\u0448\u0443\u043A \u0442\u0430 \u0415\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438",
    dreamsFolderName: "\u0413\u043E\u043B\u043E\u0432\u043D\u0430 \u043F\u0430\u043F\u043A\u0430 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430 \u0441\u043D\u0456\u0432",
    dreamsFolderDesc: "\u0417\u0430\u0433\u0430\u043B\u044C\u043D\u0430 \u043F\u0430\u043F\u043A\u0430 (\u043D\u0430\u043F\u0440\u0438\u043A\u043B\u0430\u0434, \u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0456 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F \u0430\u0431\u043E Dreams). \u041F\u043B\u0430\u0433\u0456\u043D \u0441\u0430\u043C \u0441\u0442\u0432\u043E\u0440\u0438\u0442\u044C \u043F\u0430\u043F\u043A\u0438 '\u0421\u043D\u0438', '\u0421\u0443\u0442\u043D\u043E\u0441\u0442\u0456' \u0442\u0430 \u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0432\u0441\u0435\u0440\u0435\u0434\u0438\u043D\u0456.",
    autoEmbeddingsName: "\u0410\u0432\u0442\u043E-\u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432",
    autoEmbeddingsDesc: "\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u043D\u043E \u043E\u043D\u043E\u0432\u043B\u044E\u0432\u0430\u0442\u0438 \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0456 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438 \u043F\u0456\u0441\u043B\u044F \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443",
    embeddingModelName: "\u041C\u043E\u0434\u0435\u043B\u044C \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432",
    embeddingModelDesc: "\u041C\u043E\u0434\u0435\u043B\u044C OpenAI \u0434\u043B\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u0438\u0437\u0430\u0446\u0456\u0457 (\u0437\u0430 \u0437\u0430\u043C\u043E\u0432\u0447\u0443\u0432\u0430\u043D\u043D\u044F\u043C: text-embedding-3-small)",
    thresholdName: "\u041F\u043E\u0440\u0456\u0433 \u0441\u0445\u043E\u0436\u043E\u0441\u0442\u0456 (Similarity Threshold)",
    thresholdDesc: "\u041C\u0456\u043D\u0456\u043C\u0430\u043B\u044C\u043D\u0438\u0439 \u043F\u043E\u0440\u0456\u0433 \u0441\u0445\u043E\u0436\u043E\u0441\u0442\u0456 \u0434\u043B\u044F \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 (\u0432\u0456\u0434 0.0 \u0434\u043E 1.0)",
    limitName: "\u041B\u0456\u043C\u0456\u0442 \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439",
    limitDesc: "\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u0430 \u043A\u0456\u043B\u044C\u043A\u0456\u0441\u0442\u044C \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0443 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0456 AI",
    rebuildButtonName: "\u0420\u0443\u0447\u043D\u0435 \u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0431\u0430\u0437\u0438 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439",
    rebuildButtonDesc: "\u041F\u0440\u043E\u0441\u043A\u0430\u043D\u0443\u0432\u0430\u0442\u0438 \u0432\u0441\u0456 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u043E\u0431\u0447\u0438\u0441\u043B\u0438\u0442\u0438 \u0432\u0456\u0434\u0441\u0443\u0442\u043D\u0456 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438",
    rebuildButtonText: "\u041F\u0435\u0440\u0435\u0431\u0443\u0434\u0443\u0432\u0430\u0442\u0438 \u0432\u0441\u0456 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438"
  },
  en: {
    // Dashboard
    dashboardFileName: "Dream Dashboard.md",
    dashboardTitle: "# Dream Analytics Dashboard",
    dashboardCallout: "> [!INFO] Analytics & Statistics\n> This dashboard is automatically generated by **Dream Analyzer**. It contains key Dataview queries for tracking dream stats, Dream Signs (reality checks), emotional trends, and creative ideas.",
    dashboardSectionStats: "## Journal & Lucid Dreaming Statistics",
    dashboardSectionSigns: "## Dream Signs & Reality Check Triggers\n*Most frequent symbols, characters, and places \u2014 your reality check triggers in dreams.*",
    dashboardSectionEmotions: "## Emotional Background & Psychological States\n*Emotions and internal mental states most frequently experienced in dreams.*",
    dashboardSectionCreative: "## Dream World: Concepts & Creative Ideas\n*Abstract concepts, unique locations, and vivid characters with descriptions.*",
    dashboardSectionLucid: "## Lucid Dreams (LD)\n*Journal of your successful lucid dreams.*",
    dashboardSectionRecent: "## Recent Dream Journal Entries",
    // Ribbon & Commands
    ribbonAnalyze: "Analyze dream (Dream Analyzer)",
    ribbonCreateDream: "Create dream note for today",
    cmdAnalyze: "Analyze active dream",
    cmdCreateDream: "Create dream note for today",
    cmdCreateCustomDateDream: "Create dream note for selected date...",
    cmdRebuildEmbeddings: "Rebuild entity embeddings",
    cmdResetAllData: "Reset all analyzed data and entities...",
    contextMenuAnalyze: "Analyze dream",
    // Date Modal
    dateModalTitle: "Select Dream Date",
    dateModalLabel: "Dream Date",
    dateModalButton: "Create / Open Dream",
    // Reset Modal & Settings
    resetModalTitle: "Reset All Analyzed Data and Entities",
    resetModalDesc: "This will delete all created entity notes, clear vector database files (embeddings.json), and reset analyzed AI content in all dreams to their initial template state. Your original dream texts will remain untouched.",
    resetModalConfirmButton: "Reset All",
    resetModalCancelButton: "Cancel",
    resetSuccess: "Reset dreams: {dreams}, deleted entity files: {entities}.",
    resetSectionTitle: "Reset & Clear Data",
    resetSectionDesc: "Delete all generated entities and reset dream notes to initial template state for re-analysis",
    resetButtonText: "Clear All Entities & Analysis",
    // Templater Exporter
    templateExportSuccess: "Templater / Calendar template successfully saved to {path}!",
    templateExportName: "Templater & Calendar Template",
    templateExportDesc: "Save a compatible dream note template file in Vault for Templater and Calendar plugins",
    templatePathName: "Template File Path",
    templatePathDesc: "Vault file path where template will be written (e.g. Templates/Dream Template.md)",
    templateExportButtonText: "Create / Update Template File",
    // Notices
    noActiveNote: "No active dream note open",
    openDreamNoteFirst: "Please open a dream note to analyze.",
    noApiKey: "OpenAI API key is missing! Please enter your API key in Dream Analyzer settings.",
    analyzingStep1: "Analyzing dream: generating vector embeddings...",
    analyzingStep2: "Analyzing dream: searching for similar entities...",
    analyzingStep3: "Analyzing dream: sending request to OpenAI ({model})...",
    analyzingStep4: "Creating entities and connections...",
    analyzingStep5: "Batch updating vector embeddings...",
    analysisSuccess: "Dream analyzed successfully in {sec}s!",
    analysisError: "Dream analysis error: ",
    rebuildStart: "Generating vector embeddings...",
    rebuildSuccess: "Done! Generated/updated embeddings: {count}",
    dreamAlreadyExists: "Dream note for this date already exists!",
    dreamCreated: "Created new dream note!",
    // Days & Months
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    months: [
      "01 - January",
      "02 - February",
      "03 - March",
      "04 - April",
      "05 - May",
      "06 - June",
      "07 - July",
      "08 - August",
      "09 - September",
      "10 - October",
      "11 - November",
      "12 - December"
    ],
    // Settings
    settingsTitle: "Dream Analyzer Settings",
    apiKeyName: "OpenAI API Key",
    apiKeyDesc: "Enter your secret OpenAI API Key (sk-...)",
    modelName: "OpenAI Chat Model",
    modelDesc: "Select AI model for dream analysis",
    gptDefaultLabel: "GPT-5 mini (Default)",
    sectionJournalFolder: "Dream Journal Folder Structure",
    sectionVectorSearch: "Vector Search & Embeddings",
    dreamsFolderName: "Main Dream Journal Folder",
    dreamsFolderDesc: "Main folder (e.g. Dreams or Lucid Dreaming). The plugin will automatically manage 'Dreams', 'Entities', and Dashboard subfolders inside.",
    autoEmbeddingsName: "Auto-update Embeddings",
    autoEmbeddingsDesc: "Automatically update vector embeddings after dream analysis",
    embeddingModelName: "Embedding Model",
    embeddingModelDesc: "OpenAI model for vectorization (default: text-embedding-3-small)",
    thresholdName: "Similarity Threshold",
    thresholdDesc: "Minimum similarity threshold for entities (from 0.0 to 1.0)",
    limitName: "Similar Entities Limit",
    limitDesc: "Maximum number of similar entities in AI context",
    rebuildButtonName: "Manual Entity Embeddings Update",
    rebuildButtonDesc: "Scan all entity notes and calculate missing embeddings",
    rebuildButtonText: "Rebuild All Embeddings"
  }
};
function t(key, vars) {
  const locale = getLocale();
  let template = strings[locale] && strings[locale][key] || strings["en"][key] || strings["uk"][key] || "";
  if (typeof template === "string" && vars) {
    for (const [k, v] of Object.entries(vars)) {
      template = template.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    }
  }
  return template;
}

// src/embeddings.ts
var cachedEntityDb = null;
var cachedDreamDb = null;
function clearMemoryCache() {
  cachedEntityDb = null;
  cachedDreamDb = null;
}
function getDreamsSubfolder(app, settings) {
  const root = (0, import_obsidian3.normalizePath)((settings?.dreamsFolder || "Dreams").trim());
  if (app && app.vault) {
    if (app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${root}/\u0421\u043D\u0438`))) return (0, import_obsidian3.normalizePath)(`${root}/\u0421\u043D\u0438`);
    if (app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${root}/Dreams`))) return (0, import_obsidian3.normalizePath)(`${root}/Dreams`);
  }
  const locale = getLocale();
  const sub = locale === "uk" ? "\u0421\u043D\u0438" : "Dreams";
  return (0, import_obsidian3.normalizePath)(`${root}/${sub}`);
}
function getEntitiesSubfolder(app, settings) {
  const root = (0, import_obsidian3.normalizePath)((settings?.dreamsFolder || "Dreams").trim());
  if (app && app.vault) {
    if (app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${root}/\u0421\u0443\u0442\u043D\u043E\u0441\u0442\u0456`))) return (0, import_obsidian3.normalizePath)(`${root}/\u0421\u0443\u0442\u043D\u043E\u0441\u0442\u0456`);
    if (app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${root}/Entities`))) return (0, import_obsidian3.normalizePath)(`${root}/Entities`);
  }
  const locale = getLocale();
  const sub = locale === "uk" ? "\u0421\u0443\u0442\u043D\u043E\u0441\u0442\u0456" : "Entities";
  return (0, import_obsidian3.normalizePath)(`${root}/${sub}`);
}
function getEntityEmbeddingsDbPath(app, settings) {
  const folder = getDreamsSubfolder(app, settings);
  return (0, import_obsidian3.normalizePath)(`${folder}/embeddings.json`);
}
function getDreamEmbeddingsDbPath(app, settings) {
  const folder = getDreamsSubfolder(app, settings);
  return (0, import_obsidian3.normalizePath)(`${folder}/dream_embeddings.json`);
}
function cosineSimilarity(a, b) {
  if (!Array.isArray(a) || !Array.isArray(b) || a.length === 0 || a.length !== b.length) {
    return null;
  }
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  if (normA === 0 || normB === 0) {
    return null;
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}
async function ensureParentDirectory(app, filePath) {
  const normalizedPath = (0, import_obsidian3.normalizePath)(filePath.trim());
  const dirIndex = normalizedPath.lastIndexOf("/");
  if (dirIndex > 0) {
    const dir = normalizedPath.substring(0, dirIndex);
    if (!await app.vault.adapter.exists(dir)) {
      await app.vault.createFolder(dir);
    }
  }
}
async function loadEmbeddingsDatabase(app, settings, forceReload = false) {
  const dbPath = getEntityEmbeddingsDbPath(app, settings);
  if (!forceReload && cachedEntityDb && cachedEntityDb.dbPath === dbPath) {
    return cachedEntityDb.data;
  }
  try {
    const exists = await app.vault.adapter.exists(dbPath);
    if (!exists) {
      await saveEmbeddingsDatabase(app, settings, []);
      return [];
    }
    const content = await app.vault.adapter.read(dbPath);
    const rawData = JSON.parse(content);
    const data = Array.isArray(rawData) ? rawData : [];
    const cleanData = data.filter((item) => item && item.file && app.vault.getAbstractFileByPath(item.file));
    cachedEntityDb = { dbPath, data: cleanData };
    if (cleanData.length !== data.length) {
      await saveEmbeddingsDatabase(app, settings, cleanData);
    }
    return cleanData;
  } catch (e) {
    console.warn("Could not load embeddings database:", e);
    return [];
  }
}
async function saveEmbeddingsDatabase(app, settings, database) {
  const dbPath = getEntityEmbeddingsDbPath(app, settings);
  await ensureParentDirectory(app, dbPath);
  await app.vault.adapter.write(dbPath, JSON.stringify(database, null, 2));
  cachedEntityDb = { dbPath, data: database };
}
async function loadDreamEmbeddingsDatabase(app, settings, forceReload = false) {
  const dbPath = getDreamEmbeddingsDbPath(app, settings);
  if (!forceReload && cachedDreamDb && cachedDreamDb.dbPath === dbPath) {
    return cachedDreamDb.data;
  }
  try {
    const exists = await app.vault.adapter.exists(dbPath);
    if (!exists) {
      await saveDreamEmbeddingsDatabase(app, settings, []);
      return [];
    }
    const content = await app.vault.adapter.read(dbPath);
    const rawData = JSON.parse(content);
    const data = Array.isArray(rawData) ? rawData : [];
    const cleanData = data.filter((item) => item && item.file && app.vault.getAbstractFileByPath(item.file));
    cachedDreamDb = { dbPath, data: cleanData };
    if (cleanData.length !== data.length) {
      await saveDreamEmbeddingsDatabase(app, settings, cleanData);
    }
    return cleanData;
  } catch (e) {
    console.warn("Could not load dream embeddings database:", e);
    return [];
  }
}
async function saveDreamEmbeddingsDatabase(app, settings, database) {
  const dbPath = getDreamEmbeddingsDbPath(app, settings);
  await ensureParentDirectory(app, dbPath);
  await app.vault.adapter.write(dbPath, JSON.stringify(database, null, 2));
  cachedDreamDb = { dbPath, data: database };
}
async function handleFileRename(app, settings, file, oldPath) {
  if (!(file instanceof import_obsidian3.TFile) || file.extension !== "md") return;
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  const dreamsFolder = getDreamsSubfolder(app, settings);
  let updated = false;
  if (oldPath.startsWith(entitiesFolder) || file.path.startsWith(entitiesFolder)) {
    let entityDb = await loadEmbeddingsDatabase(app, settings);
    let itemChanged = false;
    entityDb = entityDb.map((item) => {
      if (item.file === oldPath) {
        itemChanged = true;
        return {
          ...item,
          file: file.path,
          name: file.basename
        };
      }
      return item;
    });
    if (itemChanged) {
      await saveEmbeddingsDatabase(app, settings, entityDb);
      updated = true;
    }
  }
  if (oldPath.startsWith(dreamsFolder) || file.path.startsWith(dreamsFolder)) {
    let dreamDb = await loadDreamEmbeddingsDatabase(app, settings);
    let itemChanged = false;
    dreamDb = dreamDb.map((item) => {
      if (item.file === oldPath) {
        itemChanged = true;
        return {
          ...item,
          file: file.path,
          name: file.basename
        };
      }
      return item;
    });
    if (itemChanged) {
      await saveDreamEmbeddingsDatabase(app, settings, dreamDb);
      updated = true;
    }
  }
  if (updated) {
    console.log(`[Dream Analyzer] Updated vector embedding path from ${oldPath} to ${file.path}`);
  }
}
function selectSimilarEntities(dreamVector, database, threshold = 0.35, limit = 40) {
  if (!Array.isArray(dreamVector) || dreamVector.length === 0 || !Array.isArray(database)) {
    return [];
  }
  const results = [];
  for (const item of database) {
    if (!item || !item.name || !Array.isArray(item.vector)) continue;
    const score = cosineSimilarity(dreamVector, item.vector);
    if (score !== null && score >= threshold) {
      results.push({
        name: item.name,
        type: item.type || "",
        description: item.description || "",
        aliases: Array.isArray(item.aliases) ? item.aliases : [],
        file: item.file || "",
        score
      });
    }
  }
  return results.sort((a, b) => b.score - a.score).slice(0, limit);
}
function formatEntityContext(entities) {
  if (!Array.isArray(entities) || entities.length === 0) return "";
  return entities.map((item) => {
    const aliases = item.aliases && item.aliases.length ? item.aliases.join(", ") : "-";
    return [
      `- ${item.name} (${item.type})`,
      `  \u0421\u0445\u043E\u0436\u0456\u0441\u0442\u044C: ${item.score.toFixed(3)}`,
      `  \u041E\u043F\u0438\u0441: ${item.description || "-"}`,
      `  \u0410\u043B\u0456\u0430\u0441\u0438: ${aliases}`
    ].join("\n");
  }).join("\n\n");
}
async function getSimilarEntitiesContext(app, apiKey, settings, dreamVector) {
  try {
    const database = await loadEmbeddingsDatabase(app, settings);
    const matches = selectSimilarEntities(
      dreamVector,
      database,
      settings.similarityThreshold,
      settings.similarityLimit
    );
    return formatEntityContext(matches);
  } catch (error) {
    console.warn("Could not get similar entities for context:", error);
    return "";
  }
}
function analyzeDreamConnections(currentFile, currentEmbedding, currentEntities, dreamDatabase) {
  if (!Array.isArray(currentEmbedding) || currentEmbedding.length === 0 || !Array.isArray(dreamDatabase)) {
    return [];
  }
  const currentSet = new Set(currentEntities.map((e) => e.toLowerCase()));
  const results = [];
  for (const dream of dreamDatabase) {
    if (dream.file === currentFile.path || dream.name === currentFile.basename) {
      continue;
    }
    const embSim = cosineSimilarity(currentEmbedding, dream.vector) || 0;
    const validEmbSim = Math.max(embSim, 0);
    const dreamEntities = Array.isArray(dream.entities) ? dream.entities : [];
    const commonEntities = [];
    const seenCommon = /* @__PURE__ */ new Set();
    for (const entity of dreamEntities) {
      const lower = entity.toLowerCase();
      if (currentSet.has(lower) && !seenCommon.has(lower)) {
        seenCommon.add(lower);
        commonEntities.push(entity);
      }
    }
    const entityScore = currentEntities.length > 0 ? commonEntities.length / Math.max(currentEntities.length, 1) : 0;
    const finalScore = 0.5 * validEmbSim + 0.5 * Math.min(entityScore, 1);
    const scorePercent = Math.round(finalScore * 100);
    if (scorePercent >= 15 && (validEmbSim >= 0.2 || commonEntities.length > 0)) {
      results.push({
        dreamName: dream.name,
        dreamPath: dream.file,
        scorePercent,
        embeddingSimilarity: validEmbSim,
        entityScore,
        commonEntities
      });
    }
  }
  return results.sort((a, b) => b.scorePercent - a.scorePercent).slice(0, 5);
}
function formatDreamConnectionsMarkdown(connections) {
  if (!Array.isArray(connections) || connections.length === 0) {
    return "-";
  }
  return connections.map((conn) => {
    let item = `- **[[${conn.dreamName}]]** \u2014 **${conn.scorePercent}%** \u0441\u0445\u043E\u0436\u043E\u0441\u0442\u0456`;
    if (conn.commonEntities && conn.commonEntities.length > 0) {
      item += `
  - \u0421\u043F\u0456\u043B\u044C\u043D\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456:`;
      for (const entity of conn.commonEntities) {
        item += `
    - [[${entity}]]`;
      }
    }
    return item;
  }).join("\n\n");
}
async function updateEntityEmbeddings(app, apiKey, settings, forceRebuild = false, specificPaths) {
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  const allFiles = app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(entitiesFolder));
  let database = await loadEmbeddingsDatabase(app, settings, forceRebuild);
  const targets = [];
  for (const file of allFiles) {
    const cache = app.metadataCache.getFileCache(file);
    const fm = cache?.frontmatter || {};
    const isTargeted = specificPaths ? specificPaths.includes(file.path) : false;
    if (fm.embedding_status === "done" && !forceRebuild && !isTargeted) {
      continue;
    }
    const embeddingId = `emb_${Date.now()}_${file.basename}`;
    const text = `
\u041D\u0430\u0437\u0432\u0430:
${file.basename}

\u0422\u0438\u043F:
${fm.entity_type || ""}

\u041E\u043F\u0438\u0441:
${fm.description || ""}

\u0410\u043B\u0456\u0430\u0441\u0438:
${Array.isArray(fm.aliases) ? fm.aliases.join(", ") : ""}

\u0422\u0435\u0433\u0438:
${Array.isArray(fm.tags) ? fm.tags.join(", ") : ""}
`;
    targets.push({ file, text, embeddingId, fm });
  }
  if (targets.length === 0) return 0;
  const inputs = targets.map((t2) => t2.text);
  const vectors = await getBatchEmbeddings(apiKey, settings.embeddingModel, inputs);
  let updatedCount = 0;
  for (let i = 0; i < targets.length; i++) {
    const target = targets[i];
    const vector = vectors[i];
    if (!vector) continue;
    database = database.filter((item) => item.file !== target.file.path);
    database.push({
      id: target.embeddingId,
      file: target.file.path,
      name: target.file.basename,
      type: target.fm.entity_type || "",
      description: target.fm.description || "",
      aliases: Array.isArray(target.fm.aliases) ? target.fm.aliases : [],
      vector
    });
    await app.fileManager.processFrontMatter(target.file, (frontmatter) => {
      frontmatter.embedding_status = "done";
      frontmatter.embedding_id = target.embeddingId;
    });
    updatedCount++;
  }
  if (updatedCount > 0 || forceRebuild) {
    await saveEmbeddingsDatabase(app, settings, database);
  }
  return updatedCount;
}

// src/dreamCreator.ts
var import_obsidian4 = require("obsidian");
async function ensureFolder(app, path) {
  const normalizedPath = path.trim().replace(/\/$/, "");
  if (!app.vault.getAbstractFileByPath(normalizedPath)) {
    await app.vault.createFolder(normalizedPath);
  }
}
var DatePickerModal = class extends import_obsidian4.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: t("dateModalTitle") });
    let selectedDate = (0, import_obsidian4.moment)().format("YYYY-MM-DD");
    new import_obsidian4.Setting(contentEl).setName(t("dateModalLabel")).addText((text) => {
      text.inputEl.type = "date";
      text.setValue(selectedDate);
      text.onChange((value) => {
        if (value) selectedDate = value;
      });
    });
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText(t("dateModalButton")).setCta().onClick(() => {
      this.close();
      this.onSubmit(selectedDate);
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
async function createDreamNoteForDate(app, settings, targetDateInput) {
  const now = targetDateInput ? (0, import_obsidian4.moment)(targetDateInput, ["YYYY-MM-DD", "D.MM.YYYY", "DD.MM.YYYY"]) : (0, import_obsidian4.moment)();
  if (!now.isValid()) {
    new import_obsidian4.Notice("\u041D\u0435\u043A\u043E\u0440\u0435\u043A\u0442\u043D\u0438\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 \u0434\u0430\u0442\u0438");
    return;
  }
  const year = now.format("YYYY");
  const monthNum = now.format("MM");
  const locale = getLocale();
  const daysUk = ["\u043D\u0435\u0434\u0456\u043B\u044F", "\u043F\u043E\u043D\u0435\u0434\u0456\u043B\u043E\u043A", "\u0432\u0456\u0432\u0442\u043E\u0440\u043E\u043A", "\u0441\u0435\u0440\u0435\u0434\u0430", "\u0447\u0435\u0442\u0432\u0435\u0440", "\u043F'\u044F\u0442\u043D\u0438\u0446\u044F", "\u0441\u0443\u0431\u043E\u0442\u0430"];
  const monthsUk = [
    "01 - \u0441\u0456\u0447\u0435\u043D\u044C",
    "02 - \u043B\u044E\u0442\u0438\u0439",
    "03 - \u0431\u0435\u0440\u0435\u0437\u0435\u043D\u044C",
    "04 - \u043A\u0432\u0456\u0442\u0435\u043D\u044C",
    "05 - \u0442\u0440\u0430\u0432\u0435\u043D\u044C",
    "06 - \u0447\u0435\u0440\u0432\u0435\u043D\u044C",
    "07 - \u043B\u0438\u043F\u0435\u043D\u044C",
    "08 - \u0441\u0435\u0440\u043F\u0435\u043D\u044C",
    "09 - \u0432\u0435\u0440\u0435\u0441\u0435\u043D\u044C",
    "10 - \u0436\u043E\u0432\u0442\u0435\u043D\u044C",
    "11 - \u043B\u0438\u0441\u0442\u043E\u043F\u0430\u0434",
    "12 - \u0433\u0440\u0443\u0434\u0435\u043D\u044C"
  ];
  const dayIdx = parseInt(now.format("d"), 10);
  const monthIdx = parseInt(now.format("M"), 10) - 1;
  const dayName = locale === "uk" ? daysUk[dayIdx] : now.format("dddd");
  const monthFolder = locale === "uk" ? monthsUk[monthIdx] : `${monthNum} - ${now.format("MMMM")}`;
  const rootFolder = (settings.dreamsFolder || "Dreams").trim().replace(/\/$/, "");
  const dreamsSubfolder = getDreamsSubfolder(app, settings);
  const yearFolder = `${dreamsSubfolder}/${year}`;
  const folderPath = `${yearFolder}/${monthFolder}`;
  await ensureFolder(app, rootFolder);
  await ensureFolder(app, dreamsSubfolder);
  await ensureFolder(app, yearFolder);
  await ensureFolder(app, folderPath);
  const dateShort = now.format("D.MM.YYYY");
  const dateIso = now.format("YYYY-MM-DD");
  const fileName = `${dateShort} ${dayName}`;
  const filePath = `${folderPath}/${fileName}.md`;
  const existingFile = app.vault.getAbstractFileByPath(filePath);
  if (existingFile instanceof import_obsidian4.TFile) {
    new import_obsidian4.Notice(t("dreamAlreadyExists"));
    const leaf2 = app.workspace.getLeaf(false);
    await leaf2.openFile(existingFile);
    return existingFile;
  }
  const initialBody = `# \u0421\u043E\u043D

\u0422\u0435\u043A\u0441\u0442 \u0441\u043D\u0443


# AI \u0430\u043D\u0430\u043B\u0456\u0437

## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441


## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438

-
`;
  const newFile = await app.vault.create(filePath, initialBody);
  await app.fileManager.processFrontMatter(newFile, (fm) => {
    fm.type = "dream";
    fm.date = dateIso;
    fm.lucid = false;
    fm.entities_checked = false;
    fm.characters = [];
    fm.places = [];
    fm.objects = [];
    fm.emotions = [];
    fm.symbols = [];
    fm.concepts = [];
    fm.keywords = [];
  });
  new import_obsidian4.Notice(t("dreamCreated"));
  const leaf = app.workspace.getLeaf(false);
  await leaf.openFile(newFile);
  return newFile;
}
async function createTodayDreamNote(app, settings) {
  return createDreamNoteForDate(app, settings);
}
async function exportTemplaterTemplate(app, settings) {
  const templatePath = (settings.templateFilePath || "Templates/Dream Template.md").trim();
  const dreamsSubfolder = getDreamsSubfolder(app, settings);
  const dirIndex = templatePath.lastIndexOf("/");
  if (dirIndex > 0) {
    const dirPath = templatePath.substring(0, dirIndex);
    await ensureFolder(app, dirPath);
  }
  const templaterCode = `<%*
let title = tp.file.title;
let dateObj = window.moment(title, ["YYYY-MM-DD", "D.MM.YYYY", "DD.MM.YYYY"], true);

if (!dateObj.isValid()) {
    const match = String(title || "").match(/\\b(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}\\.\\d{2}\\.\\d{4})\\b/);
    if (match) {
        dateObj = window.moment(match[0], ["YYYY-MM-DD", "D.MM.YYYY", "DD.MM.YYYY"]);
    }
}

if (!dateObj || !dateObj.isValid()) {
    dateObj = window.moment();
}

const year = dateObj.format("YYYY");
const monthNum = dateObj.format("MM");

const daysUk = ["\u043D\u0435\u0434\u0456\u043B\u044F", "\u043F\u043E\u043D\u0435\u0434\u0456\u043B\u043E\u043A", "\u0432\u0456\u0432\u0442\u043E\u0440\u043E\u043A", "\u0441\u0435\u0440\u0435\u0434\u0430", "\u0447\u0435\u0442\u0432\u0435\u0440", "\u043F'\u044F\u0442\u043D\u0438\u0446\u044F", "\u0441\u0443\u0431\u043E\u0442\u0430"];
const monthsUk = [
  "01 - \u0441\u0456\u0447\u0435\u043D\u044C", "02 - \u043B\u044E\u0442\u0438\u0439", "03 - \u0431\u0435\u0440\u0435\u0437\u0435\u043D\u044C", "04 - \u043A\u0432\u0456\u0442\u0435\u043D\u044C",
  "05 - \u0442\u0440\u0430\u0432\u0435\u043D\u044C", "06 - \u0447\u0435\u0440\u0432\u0435\u043D\u044C", "07 - \u043B\u0438\u043F\u0435\u043D\u044C", "08 - \u0441\u0435\u0440\u043F\u0435\u043D\u044C",
  "09 - \u0432\u0435\u0440\u0435\u0441\u0435\u043D\u044C", "10 - \u0436\u043E\u0432\u0442\u0435\u043D\u044C", "11 - \u043B\u0438\u0441\u0442\u043E\u043F\u0430\u0434", "12 - \u0433\u0440\u0443\u0434\u0435\u043D\u044C"
];

const dayIdx = parseInt(dateObj.format("d"), 10);
const monthIdx = parseInt(dateObj.format("M"), 10) - 1;

const dayName = daysUk[dayIdx];
const monthFolder = monthsUk[monthIdx];

const baseFolder = "${dreamsSubfolder}";
const yearFolder = \`\${baseFolder}/\${year}\`;
const folder = \`\${yearFolder}/\${monthFolder}\`;

if (!app.vault.getAbstractFileByPath(baseFolder)) {
    await app.vault.createFolder(baseFolder);
}
if (!app.vault.getAbstractFileByPath(yearFolder)) {
    await app.vault.createFolder(yearFolder);
}
if (!app.vault.getAbstractFileByPath(folder)) {
    await app.vault.createFolder(folder);
}

await tp.file.move(\`\${folder}/\${dateObj.format("D.MM.YYYY")} \${dayName}\`);
-%>---
type: dream
date: <% dateObj.format("YYYY-MM-DD") %>
lucid: false
entities_checked: false

characters: []
places: []
objects: []
emotions: []
symbols: []
concepts: []
keywords: []
---

# \u0421\u043E\u043D

\u0422\u0435\u043A\u0441\u0442 \u0441\u043D\u0443


# AI \u0430\u043D\u0430\u043B\u0456\u0437

## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441


## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438

-
`;
  const existing = app.vault.getAbstractFileByPath(templatePath);
  if (existing instanceof import_obsidian4.TFile) {
    await app.vault.modify(existing, templaterCode);
  } else {
    await app.vault.create(templatePath, templaterCode);
  }
  new import_obsidian4.Notice(t("templateExportSuccess", { path: templatePath }));
}
async function ensureEntityIndexes(app, settings) {
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  const locale = getLocale();
  let indexFolderName = locale === "uk" ? "! \u0406\u043D\u0434\u0435\u043A\u0441" : "! Indexes";
  if (app.vault.getAbstractFileByPath(`${entitiesFolder}/! \u0406\u043D\u0434\u0435\u043A\u0441`)) {
    indexFolderName = "! \u0406\u043D\u0434\u0435\u043A\u0441";
  } else if (app.vault.getAbstractFileByPath(`${entitiesFolder}/! Indexes`)) {
    indexFolderName = "! Indexes";
  }
  const indexesFolderPath = `${entitiesFolder}/${indexFolderName}`;
  await ensureFolder(app, indexesFolderPath);
  for (const type of ENTITY_TYPES) {
    const categoryFolder = `${entitiesFolder}/${type.folder}`;
    await ensureFolder(app, categoryFolder);
    let fileName = locale === "uk" ? `\u0406\u043D\u0434\u0435\u043A\u0441 - ${type.folder}.md` : `Index - ${type.folder}.md`;
    const ukFile = `${indexesFolderPath}/\u0406\u043D\u0434\u0435\u043A\u0441 - ${type.folder}.md`;
    const enFile = `${indexesFolderPath}/Index - ${type.folder}.md`;
    if (app.vault.getAbstractFileByPath(ukFile)) {
      fileName = `\u0406\u043D\u0434\u0435\u043A\u0441 - ${type.folder}.md`;
    } else if (app.vault.getAbstractFileByPath(enFile)) {
      fileName = `Index - ${type.folder}.md`;
    }
    const filePath = `${indexesFolderPath}/${fileName}`;
    const title = locale === "uk" ? `\u0406\u043D\u0434\u0435\u043A\u0441 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439: ${type.folder}` : `Entity Index: ${type.folder}`;
    const desc = locale === "uk" ? `\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u0443\u0441\u0456\u0445 \u0437\u0431\u0435\u0440\u0435\u0436\u0435\u043D\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0456\u0457 **${type.folder}** \u0437 \u0457\u0445\u043D\u0456\u043C\u0438 \u043E\u043F\u0438\u0441\u0430\u043C\u0438 \u0442\u0430 \u0447\u0430\u0441\u0442\u043E\u0442\u043E\u044E \u043F\u043E\u044F\u0432 \u0443 \u0441\u043D\u0430\u0445.` : `Catalog of all saved **${type.folder}** entities with descriptions and dream frequency.`;
    const content = `# ${title}

> [!INFO] ${title}
> ${desc}

---

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "${locale === "uk" ? "\u0421\u0443\u0442\u043D\u0456\u0441\u0442\u044C" : "Entity"}",
description AS "${locale === "uk" ? "\u041E\u043F\u0438\u0441" : "Description"}",
dream_count AS "${locale === "uk" ? "\u041F\u043E\u044F\u0432 \u0443 \u0441\u043D\u0430\u0445" : "Dream Count"}",
last_seen AS "${locale === "uk" ? "\u041E\u0441\u0442\u0430\u043D\u043D\u044F \u043F\u043E\u044F\u0432\u0430" : "Last Seen"}"
FROM "${categoryFolder}"
WHERE file.name != "${fileName.replace(/\.md$/, "")}"
SORT dream_count DESC
\`\`\`
`;
    const existing = app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian4.TFile) {
      const currentContent = await app.vault.read(existing);
      if (currentContent !== content) {
        await app.vault.modify(existing, content);
      }
    } else {
      await app.vault.create(filePath, content);
    }
  }
}
async function ensureDreamDashboard(app, settings) {
  const rootFolder = (settings.dreamsFolder || "Dreams").trim().replace(/\/$/, "");
  const dreamsSubfolder = getDreamsSubfolder(app, settings);
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  const locale = getLocale();
  await ensureFolder(app, rootFolder);
  await ensureFolder(app, dreamsSubfolder);
  await ensureFolder(app, entitiesFolder);
  await ensureEntityIndexes(app, settings);
  let dashboardPath = `${rootFolder}/${t("dashboardFileName")}`;
  const ukPath = `${rootFolder}/\u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u0456\u0432.md`;
  const enPath = `${rootFolder}/Dream Dashboard.md`;
  if (app.vault.getAbstractFileByPath(ukPath)) {
    dashboardPath = ukPath;
  } else if (app.vault.getAbstractFileByPath(enPath)) {
    dashboardPath = enPath;
  }
  const indexLinks = ENTITY_TYPES.map((tObj) => {
    const idxName = locale === "uk" ? `\u0406\u043D\u0434\u0435\u043A\u0441 - ${tObj.folder}` : `Index - ${tObj.folder}`;
    return `- [[${idxName}]]`;
  }).join("\n");
  const content = `${t("dashboardTitle")}

${t("dashboardCallout")}

---

## ${locale === "uk" ? "\u0406\u043D\u0434\u0435\u043A\u0441\u0438 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439" : "Entity Category Indexes"}
${indexLinks}

---

${t("dashboardSectionStats")}

\`\`\`dataview
TABLE WITHOUT ID
  length(rows) AS "\u0412\u0441\u044C\u043E\u0433\u043E \u0441\u043D\u0456\u0432",
  length(filter(rows, (r) => r.lucid = true)) AS "\u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u0445 (\u041E\u0421)",
  round((length(filter(rows, (r) => r.lucid = true)) / length(rows)) * 100, 1) + "%" AS "% \u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043E\u0441\u0442\u0456"
FROM "${dreamsSubfolder}"
WHERE file.name != "${pathBasename(dashboardPath)}" AND file.name != "\u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u0456\u0432" AND file.name != "Dream Dashboard"
GROUP BY true
\`\`\`

---

${t("dashboardSectionSigns")}

\`\`\`dataview
TABLE WITHOUT ID
  file.link AS "\u041C\u0430\u0440\u043A\u0435\u0440 / \u0421\u0443\u0442\u043D\u0456\u0441\u0442\u044C",
  entity_type AS "\u0422\u0438\u043F",
  dream_count AS "\u041F\u043E\u044F\u0432 \u0443 \u0441\u043D\u0430\u0445",
  last_seen AS "\u041E\u0441\u0442\u0430\u043D\u043D\u044F \u043F\u043E\u044F\u0432\u0430"
FROM "${entitiesFolder}"
WHERE contains(["symbol", "character", "place"], entity_type)
SORT dream_count DESC
LIMIT 15
\`\`\`

---

${t("dashboardSectionEmotions")}

\`\`\`dataview
TABLE WITHOUT ID
  file.link AS "\u0415\u043C\u043E\u0446\u0456\u044F / \u0421\u0442\u0430\u043D",
  dream_count AS "\u0417\u0433\u0430\u0434\u043E\u043A \u0443 \u0441\u043D\u0430\u0445",
  last_seen AS "\u041E\u0441\u0442\u0430\u043D\u043D\u044F \u043F\u043E\u044F\u0432\u0430"
FROM "${entitiesFolder}"
WHERE entity_type = "emotion"
SORT dream_count DESC
LIMIT 10
\`\`\`

---

${t("dashboardSectionCreative")}

\`\`\`dataview
TABLE WITHOUT ID
  file.link AS "\u041A\u043E\u043D\u0446\u0435\u043F\u0442 / \u041B\u043E\u043A\u0430\u0446\u0456\u044F",
  entity_type AS "\u041A\u0430\u0442\u0435\u0433\u043E\u0440\u0456\u044F",
  description AS "\u041E\u043F\u0438\u0441 \u0437 \u0430\u043D\u0430\u043B\u0456\u0437\u0443",
  dream_count AS "\u041F\u043E\u044F\u0432"
FROM "${entitiesFolder}"
WHERE contains(["concept", "place", "character"], entity_type) AND description != ""
SORT dream_count DESC
LIMIT 15
\`\`\`

---

${t("dashboardSectionLucid")}

\`\`\`dataview
TABLE WITHOUT ID
  file.link AS "\u041D\u0430\u0437\u0432\u0430 \u0441\u043D\u0443",
  date AS "\u0414\u0430\u0442\u0430",
  length(characters) + length(places) + length(objects) AS "\u0421\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0443 \u0441\u043D\u0456"
FROM "${dreamsSubfolder}"
WHERE lucid = true
SORT date DESC
LIMIT 20
\`\`\`

---

${t("dashboardSectionRecent")}

\`\`\`dataview
TABLE WITHOUT ID
  file.link AS "\u0417\u0430\u043F\u0438\u0441 \u0441\u043D\u0443",
  date AS "\u0414\u0430\u0442\u0430",
  choice(lucid, "\u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u0439 (\u041E\u0421)", "\u0417\u0432\u0438\u0447\u0430\u0439\u043D\u0438\u0439") AS "\u0422\u0438\u043F \u0441\u043D\u0443",
  length(keywords) AS "\u041A\u043B\u044E\u0447\u043E\u0432\u0438\u0445 \u0441\u043B\u0456\u0432"
FROM "${dreamsSubfolder}"
WHERE file.name != "${pathBasename(dashboardPath)}" AND file.name != "\u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u0456\u0432" AND file.name != "Dream Dashboard"
SORT file.name DESC
LIMIT 15
\`\`\`
`;
  const existing = app.vault.getAbstractFileByPath(dashboardPath);
  if (existing instanceof import_obsidian4.TFile) {
    const currentContent = await app.vault.read(existing);
    if (currentContent !== content) {
      await app.vault.modify(existing, content);
    }
  } else {
    await app.vault.create(dashboardPath, content);
  }
}
function pathBasename(pathStr) {
  const idx = pathStr.lastIndexOf("/");
  const file = idx >= 0 ? pathStr.substring(idx + 1) : pathStr;
  return file.replace(/\.md$/, "");
}

// src/resetManager.ts
var import_obsidian5 = require("obsidian");
var ConfirmResetModal = class extends import_obsidian5.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: t("resetModalTitle") });
    contentEl.createEl("p", { text: t("resetModalDesc") });
    new import_obsidian5.Setting(contentEl).addButton((btn) => btn.setButtonText(t("resetModalConfirmButton")).setWarning().onClick(() => {
      this.close();
      this.onConfirm();
    })).addButton((btn) => btn.setButtonText(t("resetModalCancelButton")).onClick(() => {
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
async function resetAllDreamData(app, settings) {
  const dreamsFolder = getDreamsSubfolder(app, settings);
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  let entitiesDeleted = 0;
  let dreamsReset = 0;
  const allFiles = app.vault.getMarkdownFiles();
  const entityFiles = allFiles.filter((f) => f.path.startsWith(entitiesFolder));
  for (const file of entityFiles) {
    try {
      await app.vault.delete(file);
      entitiesDeleted++;
    } catch (e) {
      console.error("Could not delete entity file:", file.path, e);
    }
  }
  const dreamFiles = allFiles.filter((f) => f.path.startsWith(dreamsFolder));
  for (const file of dreamFiles) {
    try {
      await app.fileManager.processFrontMatter(file, (fm) => {
        fm.type = "dream";
        fm.entities_checked = false;
        fm.characters = [];
        fm.places = [];
        fm.objects = [];
        fm.emotions = [];
        fm.symbols = [];
        fm.concepts = [];
        fm.keywords = [];
      });
      let content = await app.vault.read(file);
      if (content.includes("# AI \u0430\u043D\u0430\u043B\u0456\u0437")) {
        content = content.replace(/# AI аналіз[\s\S]*/, "# AI \u0430\u043D\u0430\u043B\u0456\u0437\n\n## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441\n\n\n## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438\n\n-");
        await app.vault.modify(file, content);
      }
      dreamsReset++;
    } catch (e) {
      console.error("Could not reset dream file:", file.path, e);
    }
  }
  await saveEmbeddingsDatabase(app, settings, []);
  await saveDreamEmbeddingsDatabase(app, settings, []);
  return { dreamsReset, entitiesDeleted };
}

// src/suggest.ts
var import_obsidian6 = require("obsidian");
var FolderSuggest = class extends import_obsidian6.AbstractInputSuggest {
  constructor(app, textComponent, onSelectCallback) {
    super(app, textComponent.inputEl);
    this.textComponent = textComponent;
    this.onSelectCallback = onSelectCallback;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerInputStr = (inputStr || "").toLowerCase();
    for (const file of abstractFiles) {
      if (file instanceof import_obsidian6.TFolder) {
        if (!inputStr || file.path.toLowerCase().includes(lowerInputStr)) {
          folders.push(file);
        }
      }
    }
    return folders.slice(0, 50);
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path);
  }
  selectSuggestion(folder, evt) {
    this.textComponent.setValue(folder.path);
    this.onSelectCallback(folder.path);
    this.close();
  }
};
var FileSuggest = class extends import_obsidian6.AbstractInputSuggest {
  constructor(app, textComponent, onSelectCallback) {
    super(app, textComponent.inputEl);
    this.textComponent = textComponent;
    this.onSelectCallback = onSelectCallback;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const files = [];
    const lowerInputStr = (inputStr || "").toLowerCase();
    for (const file of abstractFiles) {
      if (file instanceof import_obsidian6.TFile) {
        if (!inputStr || file.path.toLowerCase().includes(lowerInputStr)) {
          files.push(file);
        }
      }
    }
    return files.slice(0, 50);
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file, evt) {
    this.textComponent.setValue(file.path);
    this.onSelectCallback(file.path);
    this.close();
  }
};

// src/settings.ts
var DreamAnalyzerSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian7.Setting(containerEl).setName(t("settingsTitle")).setHeading();
    new import_obsidian7.Setting(containerEl).setName(t("apiKeyName")).setDesc(t("apiKeyDesc")).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
        this.plugin.settings.openaiApiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian7.Setting(containerEl).setName(t("modelName")).setDesc(t("modelDesc")).addDropdown((dropdown) => dropdown.addOption("gpt-5-mini", t("gptDefaultLabel")).addOption("gpt-4.1-mini", "GPT-4.1 mini").addOption("gpt-5", "GPT-5").addOption("gpt-4o-mini", "GPT-4o mini").addOption("gpt-4o", "GPT-4o").addOption("o3-mini", "o3-mini").setValue(this.plugin.settings.openaiModel || "gpt-5-mini").onChange(async (value) => {
      this.plugin.settings.openaiModel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian7.Setting(containerEl).setName(t("sectionJournalFolder")).setHeading();
    new import_obsidian7.Setting(containerEl).setName(t("dreamsFolderName")).setDesc(t("dreamsFolderDesc")).addText((text) => {
      const applyFolderChange = async (val) => {
        const cleaned = (0, import_obsidian7.normalizePath)(val.trim());
        if (cleaned) {
          this.plugin.settings.dreamsFolder = cleaned;
          await this.plugin.saveSettings();
          try {
            await ensureEntityIndexes(this.app, this.plugin.settings);
            await ensureDreamDashboard(this.app, this.plugin.settings);
          } catch (e) {
            console.warn("Could not ensure dream dashboard/indexes on folder change:", e);
          }
        }
      };
      new FolderSuggest(this.app, text, async (val) => {
        text.setValue(val);
        await applyFolderChange(val);
      });
      text.setPlaceholder("Dreams").setValue(this.plugin.settings.dreamsFolder).onChange(async (value) => {
        this.plugin.settings.dreamsFolder = (0, import_obsidian7.normalizePath)(value.trim());
        await this.plugin.saveSettings();
      });
      text.inputEl.addEventListener("blur", async () => {
        await applyFolderChange(text.getValue());
      });
    });
    new import_obsidian7.Setting(containerEl).setName(t("templateExportName")).setHeading();
    new import_obsidian7.Setting(containerEl).setName(t("templatePathName")).setDesc(t("templatePathDesc")).addText((text) => {
      new FileSuggest(this.app, text, async (val) => {
        this.plugin.settings.templateFilePath = (0, import_obsidian7.normalizePath)(val.trim());
        await this.plugin.saveSettings();
      });
      text.setPlaceholder("Templates/Dream Template.md").setValue(this.plugin.settings.templateFilePath || "Templates/Dream Template.md").onChange(async (value) => {
        this.plugin.settings.templateFilePath = (0, import_obsidian7.normalizePath)(value.trim());
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian7.Setting(containerEl).setName(t("templateExportName")).setDesc(t("templateExportDesc")).addButton((button) => button.setButtonText(t("templateExportButtonText")).setCta().onClick(async () => {
      try {
        await exportTemplaterTemplate(this.app, this.plugin.settings);
      } catch (e) {
        new import_obsidian7.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0441\u0442\u0432\u043E\u0440\u0435\u043D\u043D\u044F \u0448\u0430\u0431\u043B\u043E\u043D\u0443: " + (e.message || e));
      }
    }));
    new import_obsidian7.Setting(containerEl).setName(t("sectionVectorSearch")).setHeading();
    new import_obsidian7.Setting(containerEl).setName(t("autoEmbeddingsName")).setDesc(t("autoEmbeddingsDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoUpdateEmbeddings).onChange(async (value) => {
      this.plugin.settings.autoUpdateEmbeddings = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian7.Setting(containerEl).setName(t("embeddingModelName")).setDesc(t("embeddingModelDesc")).addText((text) => text.setPlaceholder("text-embedding-3-small").setValue(this.plugin.settings.embeddingModel).onChange(async (value) => {
      this.plugin.settings.embeddingModel = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian7.Setting(containerEl).setName(t("thresholdName")).setDesc(t("thresholdDesc")).addText((text) => text.setPlaceholder("0.35").setValue(String(this.plugin.settings.similarityThreshold)).onChange(async (value) => {
      const val = parseFloat(value);
      if (!isNaN(val) && val >= 0 && val <= 1) {
        this.plugin.settings.similarityThreshold = val;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian7.Setting(containerEl).setName(t("limitName")).setDesc(t("limitDesc")).addText((text) => text.setPlaceholder("40").setValue(String(this.plugin.settings.similarityLimit)).onChange(async (value) => {
      const val = parseInt(value, 10);
      if (!isNaN(val) && val > 0) {
        this.plugin.settings.similarityLimit = val;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian7.Setting(containerEl).setName(t("rebuildButtonName")).setDesc(t("rebuildButtonDesc")).addButton((button) => button.setButtonText(t("rebuildButtonText")).onClick(async () => {
      try {
        const apiKey = await getOpenAiApiKey(this.app, this.plugin.settings);
        const notice = new import_obsidian7.Notice(t("rebuildStart"), 0);
        const count = await updateEntityEmbeddings(this.app, apiKey, this.plugin.settings, true);
        notice.hide();
        new import_obsidian7.Notice(t("rebuildSuccess", { count }));
      } catch (e) {
        new import_obsidian7.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430: " + (e.message || e));
      }
    }));
    new import_obsidian7.Setting(containerEl).setName(t("resetSectionTitle")).setHeading();
    new import_obsidian7.Setting(containerEl).setName(t("resetSectionTitle")).setDesc(t("resetSectionDesc")).addButton((button) => button.setButtonText(t("resetButtonText")).setWarning().onClick(() => {
      new ConfirmResetModal(this.app, async () => {
        try {
          const notice = new import_obsidian7.Notice("\u041E\u0447\u0438\u0449\u0435\u043D\u043D\u044F \u0434\u0430\u043D\u0438\u0445...", 0);
          const res = await resetAllDreamData(this.app, this.plugin.settings);
          notice.hide();
          new import_obsidian7.Notice(t("resetSuccess", { dreams: res.dreamsReset, entities: res.entitiesDeleted }));
        } catch (e) {
          new import_obsidian7.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u043E\u0447\u0438\u0449\u0435\u043D\u043D\u044F: " + (e.message || e));
        }
      }).open();
    }));
  }
};

// src/analyzer.ts
var import_obsidian8 = require("obsidian");
var STOP_ENTITIES_LOWER = /* @__PURE__ */ new Set([
  // Ukrainian
  "\u043E\u043F\u043E\u0432\u0456\u0434\u0430\u0447",
  "\u044F",
  "\u0441\u043D\u043E\u0432\u0438\u0434\u0435\u0446\u044C",
  "\u043C\u043E\u0454 \u0442\u0456\u043B\u043E",
  "\u0432\u043B\u0430\u0441\u043D\u0435 \u0442\u0456\u043B\u043E",
  "\u0441\u0435\u0431\u0435",
  "\u0430\u0432\u0442\u043E\u0440",
  "\u043C\u043E\u044F \u043E\u0441\u043E\u0431\u0430",
  "\u0441\u0430\u043C\u0456\u0441\u0442\u044C",
  // English
  "narrator",
  "i",
  "me",
  "myself",
  "dreamer",
  "my body",
  "self",
  "own body"
]);
function isStopEntity(name) {
  if (!name) return true;
  const lower = name.trim().toLowerCase();
  return STOP_ENTITIES_LOWER.has(lower);
}
var ProgressNotice = class {
  constructor(totalSteps = 5) {
    this.totalSteps = totalSteps;
    this.step = 1;
    this.currentMessage = "";
    this.startTime = Date.now();
    this.notice = new import_obsidian8.Notice("", 0);
    this.startTimer();
  }
  setStep(step, message) {
    this.step = step;
    this.currentMessage = message;
    this.updateText();
  }
  startTimer() {
    this.timerId = setInterval(() => {
      this.updateText();
    }, 1e3);
  }
  updateText() {
    const elapsedSec = Math.floor((Date.now() - this.startTime) / 1e3);
    this.notice.setMessage(`[${this.step}/${this.totalSteps}] ${this.currentMessage} (${elapsedSec}s)`);
  }
  close() {
    if (this.timerId) clearInterval(this.timerId);
    this.notice.hide();
  }
  getElapsedSeconds() {
    return Math.floor((Date.now() - this.startTime) / 1e3);
  }
};
async function analyzeDream(app, file, settings) {
  if (!file) {
    new import_obsidian8.Notice("\u041D\u0435\u043C\u0430\u0454 \u0432\u0456\u0434\u043A\u0440\u0438\u0442\u043E\u0457 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u043D\u0443");
    return;
  }
  let apiKey;
  try {
    apiKey = await getOpenAiApiKey(app, settings);
  } catch (error) {
    new import_obsidian8.Notice(error.message || "\u041F\u043E\u043C\u0438\u043B\u043A\u0430 OpenAI API Key");
    return;
  }
  const progress = new ProgressNotice(5);
  try {
    progress.setStep(1, "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0434\u0430\u043D\u0438\u0445 \u0441\u043D\u0443...");
    const dreamContent = await app.vault.read(file);
    const dreamEmbedding = await getEmbedding(apiKey, settings.embeddingModel, dreamContent);
    progress.setStep(2, "\u041F\u043E\u0448\u0443\u043A \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439...");
    const similarEntities = await getSimilarEntitiesContext(app, apiKey, settings, dreamEmbedding);
    const entityContext = similarEntities || "No existing similar entities found.";
    progress.setStep(3, `\u0417\u0430\u043F\u0438\u0442 \u0434\u043E OpenAI (${settings.openaiModel})...`);
    const systemPrompt = `
You analyze a personal dream journal for creating a structured Obsidian knowledge base.
Here is a list of existing entities that might match this dream:

${entityContext}

Use existing entities if they fit. Do not create a new entity if an identical or very close entity already exists.

CRITICAL LANGUAGE REQUIREMENT:
- Automatically detect the language of the provided dream text (e.g., Ukrainian, English, etc.).
- ALL returned text fields ("summary", "name", "description", "aliases", "keywords") MUST be in the EXACT SAME LANGUAGE as the dream text.
- Do NOT translate the dream content, entity names, descriptions, or keywords into another language.

STOP ENTITIES & DEDUPLICATION RULES:
- Do NOT create trivial self-referential entities representing the dreamer or narrator (e.g., "Narrator", "Dreamer", "I", "Me", "My body", "Myself", "\u041E\u043F\u043E\u0432\u0456\u0434\u0430\u0447", "\u042F", "\u0421\u043D\u043E\u0432\u0438\u0434\u0435\u0446\u044C", "\u041C\u043E\u0454 \u0442\u0456\u043B\u043E", "\u0412\u043B\u0430\u0441\u043D\u0435 \u0442\u0456\u043B\u043E", "\u0421\u0435\u0431\u0435").
- If the dreamer's identity, body transformation, or state of self is an important plot point, record this via appropriate "concepts" (e.g., "Body Transformation", "Identity Change", "\u0422\u0440\u0430\u043D\u0441\u0444\u043E\u0440\u043C\u0430\u0446\u0456\u044F \u0442\u0456\u043B\u0430", "\u0417\u043C\u0456\u043D\u0430 \u043E\u0441\u043E\u0431\u0438\u0441\u0442\u043E\u0441\u0442\u0456"), NOT via a "Narrator" character entity.
- Each entity must have a SINGLE unique name across all categories. Do NOT return duplicate entity names in different categories (e.g. if an item is an Object "Ladder", do NOT also create a Symbol "Ladder").

Return JSON ONLY.
Format:

{
"summary":"",
"characters":[],
"places":[],
"objects":[],
"emotions":[],
"symbols":[],
"concepts":[],
"keywords":[]
}

CRITICAL FORMAT RULES:
- Do NOT use [[ ]] brackets in JSON values.
- Do NOT invent entities that are not present in the dream text.
- Do NOT add entities just to fill up categories.
- If there is not enough information for a category \u2014 keep the array empty.
- The same entity must maintain a stable name across different dreams.

ENTITY OBJECT FORMAT:
In characters, places, objects, emotions, symbols, concepts arrays, return objects:
{
"name":"",
"description":"",
"aliases":[]
}

name:
Short, stable entity name in the same language as the dream text.

description:
Short factual description of the entity in this specific dream. No psychology or subjective interpretations.

aliases:
Alternative names in the same language. Empty [] if none.

ENTITY NAMING RULES:
- Keep the name short and concise.
- Use one standard form across dreams.
- Ensure names are suitable as Obsidian note titles.
- Do NOT include symbols: / \\ : * ? " < > |

CATEGORIES:
characters: Specific people, creatures, or characters with a role in the dream (EXCLUDING the narrator/dreamer).
places: Independent locations, spaces, or geographic places.
objects: Physical items that exist in the dream as distinct objects.
emotions: Feelings, emotions, or internal mental states.
symbols: Potentially recurring motifs, symbols, or imagery.
concepts: Broad abstract themes, plot events, or transformations.
keywords: 5-15 search keywords in the dream's language.

summary:
A short summary of the dream in 2-5 sentences in the dream's language.
`;
    const rawResult = await requestChatCompletion(
      apiKey,
      settings.openaiModel,
      systemPrompt,
      dreamContent
    );
    const result = {
      summary: rawResult.summary || "",
      characters: normalizeEntityArray(rawResult.characters),
      places: normalizeEntityArray(rawResult.places),
      objects: normalizeEntityArray(rawResult.objects),
      emotions: normalizeEntityArray(rawResult.emotions),
      symbols: normalizeEntityArray(rawResult.symbols),
      concepts: normalizeEntityArray(rawResult.concepts),
      keywords: normalizeStringArray(rawResult.keywords)
    };
    progress.setStep(4, "\u0421\u0442\u0432\u043E\u0440\u0435\u043D\u043D\u044F \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u0440\u043E\u0437\u0440\u0430\u0445\u0443\u043D\u043E\u043A \u0437\u0432'\u044F\u0437\u043A\u0456\u0432...");
    const modifiedEntityPaths = await createOrUpdateEntities(app, result, file, settings);
    const currentEntityNames = [
      ...result.characters,
      ...result.places,
      ...result.objects,
      ...result.symbols,
      ...result.concepts
    ].map((e) => cleanEntityName(e.name)).filter(Boolean);
    const dreamDb = await loadDreamEmbeddingsDatabase(app, settings);
    const connections = analyzeDreamConnections(file, dreamEmbedding, currentEntityNames, dreamDb);
    const connectionsMarkdown = formatDreamConnectionsMarkdown(connections);
    await app.fileManager.processFrontMatter(file, (fm) => {
      fm.type = "dream";
      fm.entities_checked = true;
      const toLinks = (arr) => arr.map((x) => `[[${cleanEntityName(x.name)}]]`);
      fm.characters = toLinks(result.characters);
      fm.places = toLinks(result.places);
      fm.objects = toLinks(result.objects);
      fm.emotions = toLinks(result.emotions);
      fm.symbols = toLinks(result.symbols);
      fm.concepts = toLinks(result.concepts);
      fm.keywords = result.keywords.map((x) => cleanEntityName(x));
    });
    const aiText = `
# AI \u0430\u043D\u0430\u043B\u0456\u0437

## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441

${result.summary || "-"}

## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438

${connectionsMarkdown}
`;
    let updatedContent = await app.vault.read(file);
    if (updatedContent.includes("# AI \u0430\u043D\u0430\u043B\u0456\u0437")) {
      updatedContent = updatedContent.replace(/# AI аналіз[\s\S]*/, aiText.trim());
    } else {
      updatedContent += `

${aiText.trim()}`;
    }
    await app.vault.modify(file, updatedContent);
    const createdDate = (0, import_obsidian8.moment)().format("YYYY-MM-DD");
    const cache = app.metadataCache.getFileCache(file);
    const dreamDate = cache && cache.frontmatter && cache.frontmatter.date ? String(cache.frontmatter.date) : createdDate;
    const updatedDreamDb = dreamDb.filter((d) => d.file !== file.path && d.name !== file.basename);
    updatedDreamDb.push({
      id: `dream_${file.basename}`,
      file: file.path,
      name: file.basename,
      date: dreamDate,
      entities: currentEntityNames,
      vector: dreamEmbedding
    });
    await saveDreamEmbeddingsDatabase(app, settings, updatedDreamDb);
    if (settings.autoUpdateEmbeddings && modifiedEntityPaths.length > 0) {
      progress.setStep(5, "\u041F\u0430\u043A\u0435\u0442\u043D\u0435 \u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432...");
      await updateEntityEmbeddings(app, apiKey, settings, false, modifiedEntityPaths);
    }
    const totalSec = progress.getElapsedSeconds();
    progress.close();
    new import_obsidian8.Notice(`\u0421\u043E\u043D \u0443\u0441\u043F\u0456\u0448\u043D\u043E \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u043E \u0437\u0430 ${totalSec}\u0441!`);
  } catch (error) {
    progress.close();
    new import_obsidian8.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443: " + (error.message || error));
    console.error("Dream analysis failed:", error);
  }
}
function normalizeEntityArray(value) {
  if (!Array.isArray(value)) return [];
  return value.map((item) => {
    if (typeof item === "string") {
      const cleaned = cleanEntityName(item);
      return { name: cleaned, description: "", aliases: [] };
    } else if (typeof item === "object" && item !== null) {
      const cleaned = cleanEntityName(item.name);
      return {
        name: cleaned,
        description: String(item.description || ""),
        aliases: Array.isArray(item.aliases) ? item.aliases.map((a) => cleanEntityName(a)).filter(Boolean) : []
      };
    }
    return { name: "", description: "", aliases: [] };
  }).filter((item) => item.name.length > 0 && !isStopEntity(item.name));
}
function normalizeStringArray(value) {
  if (!Array.isArray(value)) return [];
  return value.map((x) => cleanEntityName(x)).filter((x) => x.length > 0 && !isStopEntity(x));
}
function cleanEntityName(item) {
  let name = typeof item === "object" && item !== null ? item.name : item;
  let str = String(name || "").replace(/\[\[/g, "").replace(/\]\]/g, "").replace(/[\/\\:*?"<>|]/g, "").replace(/\s+/g, " ").trim();
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1);
}
function findExistingEntityFile(app, baseFolder, safeName) {
  for (const type of ENTITY_TYPES) {
    const categoryFolderPath = `${baseFolder}/${type.folder}`;
    const candidatePath = `${categoryFolderPath}/${safeName}.md`;
    const file = app.vault.getAbstractFileByPath(candidatePath);
    if (file instanceof import_obsidian8.TFile) {
      return file;
    }
  }
  return null;
}
async function createOrUpdateEntities(app, result, dreamFile, settings) {
  const dreamName = dreamFile.basename;
  const createdDate = (0, import_obsidian8.moment)().format("YYYY-MM-DD");
  const cache = app.metadataCache.getFileCache(dreamFile);
  const dreamDate = cache && cache.frontmatter && cache.frontmatter.date ? String(cache.frontmatter.date) : createdDate;
  const baseFolder = getEntitiesSubfolder(app, settings);
  await ensureFolder2(app, baseFolder);
  const modifiedPaths = [];
  for (const type of ENTITY_TYPES) {
    const folderPath = `${baseFolder}/${type.folder}`;
    await ensureFolder2(app, folderPath);
    const items = result[type.field] || [];
    for (const item of items) {
      const safeName = cleanEntityName(item.name);
      if (!safeName || isStopEntity(safeName)) continue;
      const existingFile = findExistingEntityFile(app, baseFolder, safeName);
      if (existingFile instanceof import_obsidian8.TFile) {
        await app.fileManager.processFrontMatter(existingFile, (fm) => {
          fm.last_seen = dreamDate;
          fm.embedding_status = "pending";
          const dreamLink = `[[${dreamName}]]`;
          if (!Array.isArray(fm.created_from)) {
            fm.created_from = fm.created_from ? [fm.created_from] : [];
          }
          if (!fm.created_from.includes(dreamLink)) {
            fm.created_from.push(dreamLink);
          }
          fm.dream_count = fm.created_from.length;
          if (item.aliases && item.aliases.length > 0) {
            if (!Array.isArray(fm.aliases)) fm.aliases = fm.aliases ? [fm.aliases] : [];
            for (const alias of item.aliases) {
              const cleanAlias = cleanEntityName(alias);
              if (cleanAlias && !isStopEntity(cleanAlias) && !fm.aliases.includes(cleanAlias)) {
                fm.aliases.push(cleanAlias);
              }
            }
          }
        });
        let entityText = await app.vault.read(existingFile);
        const updatedText = appendDreamAppearance(entityText, dreamName, item.description);
        if (entityText !== updatedText) {
          await app.vault.modify(existingFile, updatedText);
        }
        modifiedPaths.push(existingFile.path);
      } else {
        const path = `${folderPath}/${safeName}.md`;
        const bodyContent = makeEntityBodyContent(
          app,
          safeName,
          item,
          dreamName,
          settings
        );
        const newFile = await app.vault.create(path, bodyContent);
        await app.fileManager.processFrontMatter(newFile, (fm) => {
          fm.type = "entity";
          fm.entity_type = type.entity_type;
          fm.created = createdDate;
          fm.last_seen = dreamDate;
          fm.created_from = [`[[${dreamName}]]`];
          fm.dream_count = 1;
          const cleanAliases = Array.isArray(item.aliases) ? item.aliases.map((x) => cleanEntityName(x)).filter((x) => x.length > 0 && !isStopEntity(x)) : [];
          fm.aliases = cleanAliases;
          fm.tags = [type.entity_type];
          fm.description = item.description || "";
          fm.embedding_status = "pending";
          fm.embedding_id = "";
        });
        modifiedPaths.push(path);
      }
    }
  }
  return modifiedPaths;
}
async function ensureFolder2(app, path) {
  const normalizedPath = path.replace(/\/$/, "");
  if (!app.vault.getAbstractFileByPath(normalizedPath)) {
    await app.vault.createFolder(normalizedPath);
  }
}
function makeEntityBodyContent(app, name, item, dreamName, settings) {
  const dreamsFolder = getDreamsSubfolder(app, settings);
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  return `# ${name}

## \u041E\u043F\u0438\u0441


## \u041F\u043E\u044F\u0432\u0438 \u0443 \u0441\u043D\u0430\u0445

- [[${dreamName}]]: ${makeInlineText(item.description || "\u043F\u043E\u044F\u0432\u0430 \u0443 \u0441\u043D\u0456")}

## \u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430

\`\`\`dataview
TABLE WITHOUT ID
dream_count AS "\u041F\u043E\u044F\u0432 \u0443 \u0441\u043D\u0430\u0445",
last_seen AS "\u041E\u0441\u0442\u0430\u043D\u043D\u044F \u043F\u043E\u044F\u0432\u0430"
FROM ""
WHERE file.path = this.file.path
\`\`\`

## \u0421\u043D\u0438

\`\`\`dataview
LIST
FROM "${dreamsFolder}"
WHERE contains(characters, this.file.link)
   OR contains(places, this.file.link)
   OR contains(objects, this.file.link)
   OR contains(emotions, this.file.link)
   OR contains(symbols, this.file.link)
   OR contains(concepts, this.file.link)
SORT file.name DESC
LIMIT 20
\`\`\`

## \u041F\u043E\u0432'\u044F\u0437\u0430\u043D\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u0421\u0443\u0442\u043D\u0456\u0441\u0442\u044C",
entity_type AS "\u0422\u0438\u043F",
length(filter(created_from, (d) => contains(this.created_from, d))) AS "\u0421\u043F\u0456\u043B\u044C\u043D\u0438\u0445 \u0441\u043D\u0456\u0432"
FROM "${entitiesFolder}"
WHERE length(filter(created_from, (d) => contains(this.created_from, d))) > 0
AND file.path != this.file.path
SORT length(filter(created_from, (d) => contains(this.created_from, d))) DESC
LIMIT 20
\`\`\`

## \u041D\u043E\u0442\u0430\u0442\u043A\u0438

`;
}
function appendDreamAppearance(text, dreamName, description) {
  const line = `- [[${dreamName}]]: ${makeInlineText(description || "\u043F\u043E\u044F\u0432\u0430 \u0443 \u0441\u043D\u0456")}`;
  const sectionPattern = /## Появи у снах\n([\s\S]*?)(?=\n## |$)/;
  const match = text.match(sectionPattern);
  if (!match) {
    return text.replace(
      /## Статистика/,
      `## \u041F\u043E\u044F\u0432\u0438 \u0443 \u0441\u043D\u0430\u0445

${line}

## \u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430`
    );
  }
  if (match[1].includes(`[[${dreamName}]]`)) {
    return text;
  }
  return text.replace(
    sectionPattern,
    `## \u041F\u043E\u044F\u0432\u0438 \u0443 \u0441\u043D\u0430\u0445
${match[1].trim()}
${line}
`
  );
}
function makeInlineText(text) {
  return String(text || "").replace(/\s+/g, " ").trim();
}

// src/main.ts
var DreamAnalyzerPlugin = class extends import_obsidian9.Plugin {
  async onload() {
    await this.loadSettings();
    this.app.workspace.onLayoutReady(async () => {
      try {
        await ensureEntityIndexes(this.app, this.settings);
        await ensureDreamDashboard(this.app, this.settings);
      } catch (e) {
        console.warn("Could not ensure dream dashboard/indexes:", e);
      }
    });
    this.registerEvent(
      this.app.vault.on("rename", async (file, oldPath) => {
        if (file instanceof import_obsidian9.TFile) {
          await handleFileRename(this.app, this.settings, file, oldPath);
        }
      })
    );
    this.addRibbonIcon("brain", t("ribbonAnalyze"), async () => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile instanceof import_obsidian9.TFile && activeFile.extension === "md") {
        await analyzeDream(this.app, activeFile, this.settings);
      } else {
        new import_obsidian9.Notice(t("openDreamNoteFirst"));
      }
    });
    this.addRibbonIcon("calendar-plus", t("ribbonCreateDream"), async () => {
      await createTodayDreamNote(this.app, this.settings);
    });
    this.addCommand({
      id: "analyze-dream",
      name: t("cmdAnalyze"),
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile instanceof import_obsidian9.TFile && activeFile.extension === "md") {
          if (!checking) {
            analyzeDream(this.app, activeFile, this.settings);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "create-today-dream",
      name: t("cmdCreateDream"),
      callback: async () => {
        await createTodayDreamNote(this.app, this.settings);
      }
    });
    this.addCommand({
      id: "create-custom-date-dream",
      name: t("cmdCreateCustomDateDream"),
      callback: () => {
        new DatePickerModal(this.app, async (selectedDate) => {
          await createDreamNoteForDate(this.app, this.settings, selectedDate);
        }).open();
      }
    });
    this.addCommand({
      id: "rebuild-embeddings",
      name: t("cmdRebuildEmbeddings"),
      callback: async () => {
        try {
          const apiKey = await getOpenAiApiKey(this.app, this.settings);
          const notice = new import_obsidian9.Notice(t("rebuildStart"), 0);
          const count = await updateEntityEmbeddings(this.app, apiKey, this.settings, true);
          notice.hide();
          new import_obsidian9.Notice(t("rebuildSuccess", { count }));
        } catch (e) {
          new import_obsidian9.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430: " + (e.message || e));
        }
      }
    });
    this.addCommand({
      id: "reset-all-data",
      name: t("cmdResetAllData"),
      callback: () => {
        new ConfirmResetModal(this.app, async () => {
          try {
            const notice = new import_obsidian9.Notice("\u041E\u0447\u0438\u0449\u0435\u043D\u043D\u044F \u0434\u0430\u043D\u0438\u0445...", 0);
            const res = await resetAllDreamData(this.app, this.settings);
            notice.hide();
            new import_obsidian9.Notice(t("resetSuccess", { dreams: res.dreamsReset, entities: res.entitiesDeleted }));
          } catch (e) {
            new import_obsidian9.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u043E\u0447\u0438\u0449\u0435\u043D\u043D\u044F: " + (e.message || e));
          }
        }).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        const dreamsSubfolder = getDreamsSubfolder(this.settings);
        if (file instanceof import_obsidian9.TFile && file.extension === "md" && file.path.startsWith(dreamsSubfolder)) {
          menu.addItem((item) => {
            item.setTitle(t("contextMenuAnalyze")).setIcon("brain").onClick(async () => {
              await analyzeDream(this.app, file, this.settings);
            });
          });
        }
      })
    );
    this.addSettingTab(new DreamAnalyzerSettingTab(this.app, this));
    console.log("Dream Analyzer Plugin loaded");
  }
  onunload() {
    console.log("Dream Analyzer Plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    clearMemoryCache();
  }
  async saveSettings() {
    await this.saveData(this.settings);
    clearMemoryCache();
  }
};
