/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DreamAnalyzerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  openaiApiKey: "",
  openaiModel: "gpt-5-mini",
  embeddingModel: "text-embedding-3-small",
  dreamsFolder: "Dreams",
  templateFilePath: "Templates/Dream Template.md",
  similarityThreshold: 0.35,
  similarityLimit: 40,
  autoUpdateEmbeddings: true
};
var ENTITY_TYPES = [
  { field: "characters", folder: "\u041F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0456", entity_type: "character" },
  { field: "places", folder: "\u041C\u0456\u0441\u0446\u044F", entity_type: "place" },
  { field: "objects", folder: "\u041F\u0440\u0435\u0434\u043C\u0435\u0442\u0438", entity_type: "object" },
  { field: "symbols", folder: "\u0421\u0438\u043C\u0432\u043E\u043B\u0438", entity_type: "symbol" },
  { field: "emotions", folder: "\u0415\u043C\u043E\u0446\u0456\u0457", entity_type: "emotion" },
  { field: "concepts", folder: "\u041A\u043E\u043D\u0446\u0435\u043F\u0442\u0438", entity_type: "concept" }
];

// src/settings.ts
var import_obsidian7 = require("obsidian");

// src/embeddings.ts
var import_obsidian3 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");
async function getOpenAiApiKey(app, settings) {
  let key = (settings.openaiApiKey || "").trim();
  const appWithSecret = app;
  if (key && appWithSecret.secretStorage && typeof appWithSecret.secretStorage.getSecret === "function") {
    try {
      const resolvedSecret = await appWithSecret.secretStorage.getSecret(key);
      if (resolvedSecret) {
        return resolvedSecret.trim();
      }
    } catch {
    }
  }
  if (!key) {
    throw new Error("OpenAI API key \u043D\u0435 \u0432\u043A\u0430\u0437\u0430\u043D\u043E \u0443 \u043D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F\u0445 \u043F\u043B\u0430\u0433\u0456\u043D\u0430!");
  }
  return key;
}
async function getEmbedding(apiKey, model, text) {
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.openai.com/v1/embeddings",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: model || "text-embedding-3-small",
        input: text
      })
    });
    if (response.status !== 200) {
      let errorDetail = response.text;
      try {
        const errJson = JSON.parse(response.text);
        if (errJson.error?.message) {
          errorDetail = errJson.error.message;
        }
      } catch {
      }
      throw new Error(`OpenAI API Error ${response.status}: ${errorDetail}`);
    }
    const data = JSON.parse(response.text);
    if (!data.data || !data.data[0] || !data.data[0].embedding) {
      throw new Error("\u041D\u0435\u043A\u043E\u0440\u0435\u043A\u0442\u043D\u0438\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 \u0432\u0456\u0434\u043F\u043E\u0432\u0456\u0434\u0456 embeddings \u0432\u0456\u0434 OpenAI");
    }
    return data.data[0].embedding;
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    throw new Error(`\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u0457 \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u043E\u0433\u043E \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0443: ${msg}`);
  }
}
async function getBatchEmbeddings(apiKey, model, inputs) {
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.openai.com/v1/embeddings",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: model || "text-embedding-3-small",
        input: inputs
      })
    });
    if (response.status !== 200) {
      let errorDetail = response.text;
      try {
        const errJson = JSON.parse(response.text);
        if (errJson.error?.message) {
          errorDetail = errJson.error.message;
        }
      } catch {
      }
      throw new Error(`OpenAI API Error ${response.status}: ${errorDetail}`);
    }
    const data = JSON.parse(response.text);
    if (!data.data || !Array.isArray(data.data)) {
      throw new Error("\u041D\u0435\u043A\u043E\u0440\u0435\u043A\u0442\u043D\u0438\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 \u0432\u0456\u0434\u043F\u043E\u0432\u0456\u0434\u0456 embeddings \u0432\u0456\u0434 OpenAI");
    }
    const sorted = data.data.sort((a, b) => a.index - b.index);
    return sorted.map((item) => item.embedding);
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    throw new Error(`\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u0457 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432: ${msg}`);
  }
}
async function requestChatCompletion(apiKey, model, systemPrompt, userPrompt) {
  try {
    const selectedModel = model || "gpt-4o-mini";
    const payload = {
      model: selectedModel,
      messages: [
        {
          role: "system",
          content: systemPrompt
        },
        {
          role: "user",
          content: userPrompt
        }
      ],
      response_format: { type: "json_object" }
    };
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.openai.com/v1/chat/completions",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    });
    if (response.status !== 200) {
      let errorDetail = response.text;
      try {
        const errJson = JSON.parse(response.text);
        if (errJson.error?.message) {
          errorDetail = errJson.error.message;
        }
      } catch {
      }
      throw new Error(`OpenAI API Error ${response.status}: ${errorDetail}`);
    }
    const data = JSON.parse(response.text);
    const content = data.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error("\u041D\u0435\u043A\u043E\u0440\u0435\u043A\u0442\u043D\u0430 \u0432\u0456\u0434\u043F\u043E\u0432\u0456\u0434\u044C ChatCompletion \u0432\u0456\u0434 OpenAI");
    }
    const parsed = JSON.parse(content);
    if (typeof parsed === "object" && parsed !== null) {
      return parsed;
    }
    throw new Error("\u041E\u0447\u0456\u043A\u0443\u0432\u0430\u0432\u0441\u044F JSON \u043E\u0431'\u0454\u043A\u0442 \u0432\u0456\u0434 OpenAI");
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    throw new Error(`\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0437\u0430\u043F\u0438\u0442\u0443 \u0434\u043E OpenAI: ${msg}`);
  }
}

// src/i18n.ts
var import_obsidian2 = require("obsidian");
function getLocale() {
  try {
    const win = window;
    const getLangFn = win.getLanguage;
    const obsLang = typeof getLangFn === "function" ? String(getLangFn()).toLowerCase() : "";
    if (obsLang) {
      if (obsLang.startsWith("uk") || obsLang.startsWith("ua")) {
        return "uk";
      }
      return "en";
    }
    const momentLang = (import_obsidian2.moment.locale() || "").toLowerCase();
    if (momentLang.startsWith("uk") || momentLang.startsWith("ua")) {
      return "uk";
    }
  } catch {
  }
  return "en";
}
var strings = {
  uk: {
    // Dashboard
    dashboardFileName: "\u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u0456\u0432.md",
    dashboardTitle: "# \u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u044C \u0442\u0430 \u0430\u043D\u0430\u043B\u0456\u0442\u0438\u043A\u0438",
    dashboardCallout: "> [!INFO] \u0410\u043D\u0430\u043B\u0456\u0442\u0438\u043A\u0430 \u0442\u0430 \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430\n> \u0426\u0435\u0439 \u0434\u0430\u0448\u0431\u043E\u0440\u0434 \u0430\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u043D\u043E \u0441\u0442\u0432\u043E\u0440\u0435\u043D\u043E \u043F\u043B\u0430\u0433\u0456\u043D\u043E\u043C **Dream Analyzer**. \u0412\u0456\u043D \u043C\u0456\u0441\u0442\u0438\u0442\u044C \u043A\u043B\u044E\u0447\u043E\u0432\u0456 Dataview-\u0437\u0430\u043F\u0438\u0442\u0438 \u0434\u043B\u044F \u0432\u0456\u0434\u0441\u0442\u0435\u0436\u0435\u043D\u043D\u044F \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0438 \u0441\u043D\u0456\u0432, \u043C\u0430\u0440\u043A\u0435\u0440\u0456\u0432 \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043E\u0441\u0442\u0456 (Dream Signs), \u0435\u043C\u043E\u0446\u0456\u0439\u043D\u043E\u0433\u043E \u0444\u043E\u043D\u0443 \u0442\u0430 \u0456\u0434\u0435\u0439 \u0434\u043B\u044F \u0442\u0432\u043E\u0440\u0447\u043E\u0441\u0442\u0456.",
    dashboardSectionStats: "## \u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430 \u0442\u0430 \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043E\u0441\u0442\u0456 (\u041E\u0421)",
    dashboardSectionSigns: "## \u041C\u0430\u0440\u043A\u0435\u0440\u0438 \u0441\u043D\u0456\u0432 \u0434\u043B\u044F \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043D\u044F (Dream Signs)\n*\u041D\u0430\u0439\u0447\u0430\u0441\u0442\u0456\u0448\u0456 \u0441\u0438\u043C\u0432\u043E\u043B\u0438, \u043F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0456 \u0442\u0430 \u043C\u0456\u0441\u0446\u044F \u2014 \u0432\u0430\u0448\u0456 \u0442\u0440\u0438\u0433\u0435\u0440\u0438 \u0434\u043B\u044F \u043F\u0435\u0440\u0435\u0432\u0456\u0440\u043A\u0438 \u0440\u0435\u0430\u043B\u044C\u043D\u043E\u0441\u0442\u0456 \u0443 \u0441\u043D\u0456.*",
    dashboardSectionEmotions: "## \u0415\u043C\u043E\u0446\u0456\u0439\u043D\u0438\u0439 \u0444\u043E\u043D \u0442\u0430 \u043F\u0441\u0438\u0445\u043E\u043B\u043E\u0433\u0456\u0447\u043D\u0456 \u0441\u0442\u0430\u043D\u0438\n*\u0415\u043C\u043E\u0446\u0456\u0457 \u0442\u0430 \u0432\u043D\u0443\u0442\u0440\u0456\u0448\u043D\u0456 \u0441\u0442\u0430\u043D\u0438, \u044F\u043A\u0456 \u043D\u0430\u0439\u0447\u0430\u0441\u0442\u0456\u0448\u0435 \u0432\u0438\u043D\u0438\u043A\u0430\u044E\u0442\u044C \u0443 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F\u0445.*",
    dashboardSectionCreative: "## \u0421\u0432\u0456\u0442 \u0441\u043D\u0456\u0432: \u041A\u043E\u043D\u0446\u0435\u043F\u0442\u0438 & \u0406\u0434\u0435\u0457 \u0434\u043B\u044F \u0442\u0432\u043E\u0440\u0447\u043E\u0441\u0442\u0456 \u0442\u0430 \u043A\u043D\u0438\u0433\n*\u0410\u0431\u0441\u0442\u0440\u0430\u043A\u0442\u043D\u0456 \u0456\u0434\u0435\u0457, \u0443\u043D\u0456\u043A\u0430\u043B\u044C\u043D\u0456 \u043B\u043E\u043A\u0430\u0446\u0456\u0457 \u0442\u0430 \u044F\u0441\u043A\u0440\u0430\u0432\u0456 \u043F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0456 \u0437 \u043E\u043F\u0438\u0441\u043E\u043C.*",
    dashboardSectionLucid: "## \u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0456 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F (\u041E\u0421)\n*\u0416\u0443\u0440\u043D\u0430\u043B \u0432\u0430\u0448\u0438\u0445 \u0443\u0441\u043F\u0456\u0448\u043D\u0438\u0445 \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u0445 \u0441\u043D\u0456\u0432.*",
    dashboardSectionRecent: "## \u041E\u0441\u0442\u0430\u043D\u043D\u0456 \u0437\u0430\u043F\u0438\u0441\u0438 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430",
    // Ribbon & Commands
    ribbonAnalyze: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u0432\u0430\u0442\u0438 \u0441\u043E\u043D (Dream Analyzer)",
    ribbonCreateDream: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 \u0441\u043E\u043D \u043D\u0430 \u0441\u044C\u043E\u0433\u043E\u0434\u043D\u0456",
    cmdAnalyze: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u0432\u0430\u0442\u0438 \u0430\u043A\u0442\u0438\u0432\u043D\u0438\u0439 \u0441\u043E\u043D",
    cmdCreateDream: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 \u0441\u043E\u043D \u043D\u0430 \u0441\u044C\u043E\u0433\u043E\u0434\u043D\u0456",
    cmdCreateCustomDateDream: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 \u0441\u043E\u043D \u0437\u0430 \u043E\u0431\u0440\u0430\u043D\u0443 \u0434\u0430\u0442\u0443...",
    cmdRebuildEmbeddings: "\u041E\u043D\u043E\u0432\u0438\u0442\u0438 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439",
    cmdResetAllData: "\u0421\u043A\u0438\u043D\u0443\u0442\u0438 \u0432\u0441\u0456 \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u0456 \u0434\u0430\u043D\u0456 \u0442\u0430 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456...",
    contextMenuAnalyze: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u0432\u0430\u0442\u0438 \u0441\u043E\u043D",
    // Date Modal
    dateModalTitle: "\u041E\u0431\u0435\u0440\u0456\u0442\u044C \u0434\u0430\u0442\u0443 \u0441\u043D\u0443",
    dateModalLabel: "\u0414\u0430\u0442\u0430 \u0441\u043D\u0443",
    dateModalButton: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 / \u0412\u0456\u0434\u043A\u0440\u0438\u0442\u0438 \u0441\u043E\u043D",
    // Reset Modal & Settings
    resetModalTitle: "\u041E\u0447\u0438\u0449\u0435\u043D\u043D\u044F \u0432\u0441\u0456\u0445 \u0437\u043D\u0430\u0439\u0434\u0435\u043D\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u043E\u0457 \u0431\u0430\u0437\u0438",
    resetModalDesc: "\u0426\u0435 \u0432\u0438\u0434\u0430\u043B\u0438\u0442\u044C \u0443\u0441\u0456 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439, \u043E\u0431\u043D\u0443\u043B\u0438\u0442\u044C \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0456 \u0431\u0430\u0437\u0438 (embeddings.json) \u0442\u0430 \u0441\u043A\u0438\u043D\u0435 \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u0438\u0439 AI-\u0432\u043C\u0456\u0441\u0442 \u0443\u0441\u0456\u0445 \u0441\u043D\u0456\u0432 \u0434\u043E \u043F\u043E\u0447\u0430\u0442\u043A\u043E\u0432\u043E\u0433\u043E \u0441\u0442\u0430\u043D\u0443. \u0422\u0435\u043A\u0441\u0442\u0438 \u0441\u0430\u043C\u0438\u0445 \u0441\u043D\u0456\u0432 \u0437\u0430\u043B\u0438\u0448\u0430\u0442\u044C\u0441\u044F \u043D\u0435\u0434\u043E\u0442\u043E\u0440\u043A\u0430\u043D\u0438\u043C\u0438.",
    resetModalConfirmButton: "\u0421\u043A\u0438\u043D\u0443\u0442\u0438 \u0432\u0441\u0435",
    resetModalCancelButton: "\u0421\u043A\u0430\u0441\u0443\u0432\u0430\u0442\u0438",
    resetSuccess: "\u0421\u043A\u0438\u043D\u0443\u0442\u043E \u0441\u043D\u0456\u0432: {dreams}, \u0432\u0438\u0434\u0430\u043B\u0435\u043D\u043E \u0444\u0430\u0439\u043B\u0456\u0432 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439: {entities}.",
    resetSectionTitle: "\u0421\u043A\u0438\u043D\u0443\u0442\u0438 \u0442\u0430 \u043E\u0447\u0438\u0441\u0442\u0438\u0442\u0438 \u0434\u0430\u043D\u0456",
    resetSectionDesc: "\u0412\u0438\u0434\u0430\u043B\u0438\u0442\u0438 \u0432\u0441\u0456 \u0437\u0433\u0435\u043D\u0435\u0440\u043E\u0432\u0430\u043D\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456 \u0442\u0430 \u0441\u043A\u0438\u043D\u0443\u0442\u0438 \u0441\u043D\u0438 \u0434\u043E \u043F\u043E\u0447\u0430\u0442\u043A\u043E\u0432\u043E\u0433\u043E \u0441\u0442\u0430\u043D\u0443 \u0434\u043B\u044F \u043F\u043E\u0432\u0442\u043E\u0440\u043D\u043E\u0433\u043E \u0430\u043D\u0430\u043B\u0456\u0437\u0443",
    resetButtonText: "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u0438 \u0432\u0441\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456 \u0442\u0430 \u0430\u043D\u0430\u043B\u0456\u0437",
    // Templater Exporter
    templateExportSuccess: "\u0428\u0430\u0431\u043B\u043E\u043D \u0434\u043B\u044F Templater / Calendar \u0443\u0441\u043F\u0456\u0448\u043D\u043E \u0437\u0431\u0435\u0440\u0435\u0436\u0435\u043D\u043E \u0443 {path}!",
    templateExportName: "\u0428\u0430\u0431\u043B\u043E\u043D \u0434\u043B\u044F Templater & Calendar",
    templateExportDesc: "\u0417\u0431\u0435\u0440\u0435\u0433\u0442\u0438 \u0441\u0443\u043C\u0456\u0441\u043D\u0438\u0439 \u0448\u0430\u0431\u043B\u043E\u043D \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u043D\u0443 \u0443 Vault \u0434\u043B\u044F \u043F\u043B\u0430\u0433\u0456\u043D\u0456\u0432 Templater \u0442\u0430 Calendar",
    templatePathName: "\u0428\u043B\u044F\u0445 \u0434\u043E \u0444\u0430\u0439\u043B\u0443 \u0448\u0430\u0431\u043B\u043E\u043D\u0443",
    templatePathDesc: "\u0424\u0430\u0439\u043B \u0443 \u0441\u0445\u043E\u0432\u0438\u0449\u0456, \u043A\u0443\u0434\u0438 \u0431\u0443\u0434\u0435 \u0437\u0430\u043F\u0438\u0441\u0430\u043D\u043E \u0448\u0430\u0431\u043B\u043E\u043D (\u043D\u0430\u043F\u0440\u0438\u043A\u043B\u0430\u0434, Templates/Dream Template.md)",
    templateExportButtonText: "\u0421\u0442\u0432\u043E\u0440\u0438\u0442\u0438 / \u043E\u043D\u043E\u0432\u0438\u0442\u0438 \u0444\u0430\u0439\u043B \u0448\u0430\u0431\u043B\u043E\u043D\u0443",
    // Notices
    noActiveNote: "\u041D\u0435\u043C\u0430\u0454 \u0432\u0456\u0434\u043A\u0440\u0438\u0442\u043E\u0457 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u043D\u0443",
    openDreamNoteFirst: "\u0411\u0443\u0434\u044C \u043B\u0430\u0441\u043A\u0430, \u0432\u0456\u0434\u043A\u0440\u0438\u0439\u0442\u0435 \u043D\u043E\u0442\u0430\u0442\u043A\u0443 \u0441\u043D\u0443 \u0434\u043B\u044F \u0430\u043D\u0430\u043B\u0456\u0437\u0443.",
    noApiKey: "OpenAI API key \u043D\u0435 \u0432\u043A\u0430\u0437\u0430\u043D\u043E! \u0411\u0443\u0434\u044C \u043B\u0430\u0441\u043A\u0430, \u0432\u043A\u0430\u0436\u0456\u0442\u044C API \u043A\u043B\u044E\u0447 \u0443 \u043D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F\u0445 \u043F\u043B\u0430\u0433\u0456\u043D\u0430 Dream Analyzer.",
    analyzingStep1: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u044E \u0441\u043E\u043D: \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0434\u0430\u043D\u0438\u0445...",
    analyzingStep2: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u044E \u0441\u043E\u043D: \u043F\u043E\u0448\u0443\u043A \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439...",
    analyzingStep3: "\u0410\u043D\u0430\u043B\u0456\u0437\u0443\u044E \u0441\u043E\u043D: \u0437\u0430\u043F\u0438\u0442 \u0434\u043E OpenAI ({model})...",
    analyzingStep4: "\u0421\u0442\u0432\u043E\u0440\u0435\u043D\u043D\u044F \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u0440\u043E\u0437\u0440\u0430\u0445\u0443\u043D\u043E\u043A \u0437\u0432'\u044F\u0437\u043A\u0456\u0432...",
    analyzingStep5: "\u041F\u0430\u043A\u0435\u0442\u043D\u0435 \u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432...",
    analysisSuccess: "\u0421\u043E\u043D \u0443\u0441\u043F\u0456\u0448\u043D\u043E \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u043E \u0437\u0430 {sec}\u0441!",
    analysisError: "\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443: ",
    rebuildStart: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432...",
    rebuildSuccess: "\u0413\u043E\u0442\u043E\u0432\u043E! \u0417\u0433\u0435\u043D\u0435\u0440\u043E\u0432\u0430\u043D\u043E/\u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043E \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432: {count}",
    dreamAlreadyExists: "\u041D\u043E\u0442\u0430\u0442\u043A\u0430 \u0441\u043D\u0443 \u043D\u0430 \u0446\u044E \u0434\u0430\u0442\u0443 \u0432\u0436\u0435 \u0456\u0441\u043D\u0443\u0454!",
    dreamCreated: "\u0421\u0442\u0432\u043E\u0440\u0435\u043D\u043E \u043D\u043E\u0432\u0443 \u043D\u043E\u0442\u0430\u0442\u043A\u0443 \u0441\u043D\u0443!",
    // Settings
    settingsTitle: "\u041D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F Dream Analyzer",
    apiKeyName: "OpenAI API Key",
    apiKeyDesc: "\u0412\u0432\u0435\u0434\u0456\u0442\u044C \u0441\u0432\u0456\u0439 \u0441\u0435\u043A\u0440\u0435\u0442\u043D\u0438\u0439 API \u043A\u043B\u044E\u0447 OpenAI (sk-...)",
    modelName: "\u041C\u043E\u0434\u0435\u043B\u044C OpenAI Chat",
    modelDesc: "\u0412\u0438\u0431\u0435\u0440\u0456\u0442\u044C \u043C\u043E\u0434\u0435\u043B\u044C AI \u0434\u043B\u044F \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443",
    gptDefaultLabel: "GPT-5 mini (\u0417\u0430 \u0437\u0430\u043C\u043E\u0432\u0447\u0443\u0432\u0430\u043D\u043D\u044F\u043C)",
    sectionJournalFolder: "\u0421\u0442\u0440\u0443\u043A\u0442\u0443\u0440\u0430 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430 \u0441\u043D\u0456\u0432",
    sectionVectorSearch: "\u0412\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0439 \u043F\u043E\u0448\u0443\u043A \u0442\u0430 \u0415\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438",
    dreamsFolderName: "\u0413\u043E\u043B\u043E\u0432\u043D\u0430 \u043F\u0430\u043F\u043A\u0430 \u0449\u043E\u0434\u0435\u043D\u043D\u0438\u043A\u0430 \u0441\u043D\u0456\u0432",
    dreamsFolderDesc: "\u0417\u0430\u0433\u0430\u043B\u044C\u043D\u0430 \u043F\u0430\u043F\u043A\u0430 (\u043D\u0430\u043F\u0440\u0438\u043A\u043B\u0430\u0434, \u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0456 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F \u0430\u0431\u043E Dreams). \u041F\u043B\u0430\u0433\u0456\u043D \u0441\u0430\u043C \u0441\u0442\u0432\u043E\u0440\u0438\u0442\u044C \u043F\u0430\u043F\u043A\u0438 '\u0421\u043D\u0438', '\u0421\u0443\u0442\u043D\u043E\u0441\u0442\u0456' \u0442\u0430 \u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0432\u0441\u0435\u0440\u0435\u0434\u0438\u043D\u0456.",
    autoEmbeddingsName: "\u0410\u0432\u0442\u043E-\u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432",
    autoEmbeddingsDesc: "\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u043D\u043E \u043E\u043D\u043E\u0432\u043B\u044E\u0432\u0430\u0442\u0438 \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0456 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438 \u043F\u0456\u0441\u043B\u044F \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443",
    embeddingModelName: "\u041C\u043E\u0434\u0435\u043B\u044C \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432",
    embeddingModelDesc: "\u041C\u043E\u0434\u0435\u043B\u044C OpenAI \u0434\u043B\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u0438\u0437\u0430\u0446\u0456\u0457 (\u0437\u0430 \u0437\u0430\u043C\u043E\u0432\u0447\u0443\u0432\u0430\u043D\u043D\u044F\u043C: text-embedding-3-small)",
    thresholdName: "\u041F\u043E\u0440\u0456\u0433 \u0441\u0445\u043E\u0436\u043E\u0441\u0442\u0456 (Similarity Threshold)",
    thresholdDesc: "\u041C\u0456\u043D\u0456\u043C\u0430\u043B\u044C\u043D\u0438\u0439 \u043F\u043E\u0440\u0456\u0433 \u0441\u0445\u043E\u0436\u043E\u0441\u0442\u0456 \u0434\u043B\u044F \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 (\u0432\u0456\u0434 0.0 \u0434\u043E 1.0)",
    limitName: "\u041B\u0456\u043C\u0456\u0442 \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439",
    limitDesc: "\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u0430 \u043A\u0456\u043B\u044C\u043A\u0456\u0441\u0442\u044C \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0443 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0456 AI",
    rebuildButtonName: "\u0420\u0443\u0447\u043D\u0435 \u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0431\u0430\u0437\u0438 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439",
    rebuildButtonDesc: "\u041F\u0440\u043E\u0441\u043A\u0430\u043D\u0443\u0432\u0430\u0442\u0438 \u0432\u0441\u0456 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u043E\u0431\u0447\u0438\u0441\u043B\u0438\u0442\u0438 \u0432\u0456\u0434\u0441\u0443\u0442\u043D\u0456 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438",
    rebuildButtonText: "\u041F\u0435\u0440\u0435\u0431\u0443\u0434\u0443\u0432\u0430\u0442\u0438 \u0432\u0441\u0456 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0438"
  },
  en: {
    // Dashboard
    dashboardFileName: "Dream Dashboard.md",
    dashboardTitle: "# Dream Analytics Dashboard",
    dashboardCallout: "> [!INFO] Analytics & Statistics\n> This dashboard is automatically generated by **Dream Analyzer**. It contains key Dataview queries for tracking dream stats, Dream Signs (reality checks), emotional trends, and creative ideas.",
    dashboardSectionStats: "## Journal & Lucid Dreaming Statistics",
    dashboardSectionSigns: "## Dream Signs & Reality Check Triggers\n*Most frequent symbols, characters, and places \u2014 your reality check triggers in dreams.*",
    dashboardSectionEmotions: "## Emotional Background & Psychological States\n*Emotions and internal mental states most frequently experienced in dreams.*",
    dashboardSectionCreative: "## Dream World: Concepts & Creative Ideas\n*Abstract concepts, unique locations, and vivid characters with descriptions.*",
    dashboardSectionLucid: "## Lucid Dreams (LD)\n*Journal of your successful lucid dreams.*",
    dashboardSectionRecent: "## Recent Dream Journal Entries",
    // Ribbon & Commands
    ribbonAnalyze: "Analyze dream (Dream Analyzer)",
    ribbonCreateDream: "Create dream note for today",
    cmdAnalyze: "Analyze active dream",
    cmdCreateDream: "Create dream note for today",
    cmdCreateCustomDateDream: "Create dream note for selected date...",
    cmdRebuildEmbeddings: "Rebuild entity embeddings",
    cmdResetAllData: "Reset all analyzed data and entities...",
    contextMenuAnalyze: "Analyze dream",
    // Date Modal
    dateModalTitle: "Select Dream Date",
    dateModalLabel: "Dream Date",
    dateModalButton: "Create / Open Dream",
    // Reset Modal & Settings
    resetModalTitle: "Reset All Analyzed Data and Entities",
    resetModalDesc: "This will delete all created entity notes, clear vector database files (embeddings.json), and reset analyzed AI content in all dreams to their initial template state. Your original dream texts will remain untouched.",
    resetModalConfirmButton: "Reset All",
    resetModalCancelButton: "Cancel",
    resetSuccess: "Reset dreams: {dreams}, deleted entity files: {entities}.",
    resetSectionTitle: "Reset & Clear Data",
    resetSectionDesc: "Delete all generated entities and reset dream notes to initial template state for re-analysis",
    resetButtonText: "Clear All Entities & Analysis",
    // Templater Exporter
    templateExportSuccess: "Templater / Calendar template successfully saved to {path}!",
    templateExportName: "Templater & Calendar Template",
    templateExportDesc: "Save a compatible dream note template file in Vault for Templater and Calendar plugins",
    templatePathName: "Template File Path",
    templatePathDesc: "Vault file path where template will be written (e.g. Templates/Dream Template.md)",
    templateExportButtonText: "Create / Update Template File",
    // Notices
    noActiveNote: "No active dream note open",
    openDreamNoteFirst: "Please open a dream note to analyze.",
    noApiKey: "OpenAI API key is missing! Please enter your API key in Dream Analyzer settings.",
    analyzingStep1: "Analyzing dream: generating vector embeddings...",
    analyzingStep2: "Analyzing dream: searching for similar entities...",
    analyzingStep3: "Analyzing dream: sending request to OpenAI ({model})...",
    analyzingStep4: "Creating entities and connections...",
    analyzingStep5: "Batch updating vector embeddings...",
    analysisSuccess: "Dream analyzed successfully in {sec}s!",
    analysisError: "Dream analysis error: ",
    rebuildStart: "Generating vector embeddings...",
    rebuildSuccess: "Done! Generated/updated embeddings: {count}",
    dreamAlreadyExists: "Dream note for this date already exists!",
    dreamCreated: "Created new dream note!",
    // Settings
    settingsTitle: "Dream Analyzer Settings",
    apiKeyName: "OpenAI API Key",
    apiKeyDesc: "Enter your secret OpenAI API Key (sk-...)",
    modelName: "OpenAI Chat Model",
    modelDesc: "Select AI model for dream analysis",
    gptDefaultLabel: "GPT-5 mini (Default)",
    sectionJournalFolder: "Dream Journal Folder Structure",
    sectionVectorSearch: "Vector Search & Embeddings",
    dreamsFolderName: "Main Dream Journal Folder",
    dreamsFolderDesc: "Main folder (e.g. Dreams or Lucid Dreaming). The plugin will automatically manage 'Dreams', 'Entities', and Dashboard subfolders inside.",
    autoEmbeddingsName: "Auto-update Embeddings",
    autoEmbeddingsDesc: "Automatically update vector embeddings after dream analysis",
    embeddingModelName: "Embedding Model",
    embeddingModelDesc: "OpenAI model for vectorization (default: text-embedding-3-small)",
    thresholdName: "Similarity Threshold",
    thresholdDesc: "Minimum similarity threshold for entities (from 0.0 to 1.0)",
    limitName: "Similar Entities Limit",
    limitDesc: "Maximum number of similar entities in AI context",
    rebuildButtonName: "Manual Entity Embeddings Update",
    rebuildButtonDesc: "Scan all entity notes and calculate missing embeddings",
    rebuildButtonText: "Rebuild All Embeddings"
  }
};
var lists = {
  uk: {
    days: ["\u043D\u0435\u0434\u0456\u043B\u044F", "\u043F\u043E\u043D\u0435\u0434\u0456\u043B\u043E\u043A", "\u0432\u0456\u0432\u0442\u043E\u0440\u043E\u043A", "\u0441\u0435\u0440\u0435\u0434\u0430", "\u0447\u0435\u0442\u0432\u0435\u0440", "\u043F'\u044F\u0442\u043D\u0438\u0446\u044F", "\u0441\u0443\u0431\u043E\u0442\u0430"],
    months: [
      "01 - \u0441\u0456\u0447\u0435\u043D\u044C",
      "02 - \u043B\u044E\u0442\u0438\u0439",
      "03 - \u0431\u0435\u0440\u0435\u0437\u0435\u043D\u044C",
      "04 - \u043A\u0432\u0456\u0442\u0435\u043D\u044C",
      "05 - \u0442\u0440\u0430\u0432\u0435\u043D\u044C",
      "06 - \u0447\u0435\u0440\u0432\u0435\u043D\u044C",
      "07 - \u043B\u0438\u043F\u0435\u043D\u044C",
      "08 - \u0441\u0435\u0440\u043F\u0435\u043D\u044C",
      "09 - \u0432\u0435\u0440\u0435\u0441\u0435\u043D\u044C",
      "10 - \u0436\u043E\u0432\u0442\u0435\u043D\u044C",
      "11 - \u043B\u0438\u0441\u0442\u043E\u043F\u0430\u0434",
      "12 - \u0433\u0440\u0443\u0434\u0435\u043D\u044C"
    ]
  },
  en: {
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    months: [
      "01 - January",
      "02 - February",
      "03 - March",
      "04 - April",
      "05 - May",
      "06 - June",
      "07 - July",
      "08 - August",
      "09 - September",
      "10 - October",
      "11 - November",
      "12 - December"
    ]
  }
};
function t(key, vars) {
  const locale = getLocale();
  let template = strings[locale][key] || strings["en"][key] || strings["uk"][key] || "";
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      template = template.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    }
  }
  return template;
}
function tList(key) {
  const locale = getLocale();
  return lists[locale][key] || lists["en"][key] || lists["uk"][key] || [];
}

// src/embeddings.ts
var cachedEntityDb = null;
var cachedDreamDb = null;
function clearMemoryCache() {
  cachedEntityDb = null;
  cachedDreamDb = null;
}
function getDreamsSubfolder(app, settings) {
  const base = (0, import_obsidian3.normalizePath)(settings.dreamsFolder.trim() || "Dreams");
  const lang = getLocale();
  const subname = lang === "uk" ? "\u0421\u043D\u0438" : "Dreams";
  return (0, import_obsidian3.normalizePath)(`${base}/${subname}`);
}
function getEntitiesSubfolder(app, settings) {
  const base = (0, import_obsidian3.normalizePath)(settings.dreamsFolder.trim() || "Dreams");
  const lang = getLocale();
  const subname = lang === "uk" ? "\u0421\u0443\u0442\u043D\u043E\u0441\u0442\u0456" : "Entities";
  return (0, import_obsidian3.normalizePath)(`${base}/${subname}`);
}
function getEmbeddingsPath(app, settings) {
  const base = (0, import_obsidian3.normalizePath)(settings.dreamsFolder.trim() || "Dreams");
  return (0, import_obsidian3.normalizePath)(`${base}/embeddings.json`);
}
function getDreamEmbeddingsPath(app, settings) {
  const base = (0, import_obsidian3.normalizePath)(settings.dreamsFolder.trim() || "Dreams");
  return (0, import_obsidian3.normalizePath)(`${base}/dream_embeddings.json`);
}
async function loadEmbeddingsDatabase(app, settings) {
  const dbPath = getEmbeddingsPath(app, settings);
  if (cachedEntityDb && cachedEntityDb.dbPath === dbPath) {
    return cachedEntityDb.data;
  }
  try {
    const file = app.vault.getAbstractFileByPath(dbPath);
    if (file instanceof import_obsidian3.TFile) {
      const content = await app.vault.read(file);
      const parsed = JSON.parse(content);
      if (Array.isArray(parsed)) {
        cachedEntityDb = { dbPath, data: parsed };
        return parsed;
      }
    }
  } catch {
  }
  cachedEntityDb = { dbPath, data: [] };
  return [];
}
async function saveEmbeddingsDatabase(app, settings, data) {
  const dbPath = getEmbeddingsPath(app, settings);
  cachedEntityDb = { dbPath, data };
  const jsonContent = JSON.stringify(data, null, 2);
  const file = app.vault.getAbstractFileByPath(dbPath);
  if (file instanceof import_obsidian3.TFile) {
    await app.vault.modify(file, jsonContent);
  } else {
    await app.vault.create(dbPath, jsonContent);
  }
}
async function loadDreamEmbeddingsDatabase(app, settings) {
  const dbPath = getDreamEmbeddingsPath(app, settings);
  if (cachedDreamDb && cachedDreamDb.dbPath === dbPath) {
    return cachedDreamDb.data;
  }
  try {
    const file = app.vault.getAbstractFileByPath(dbPath);
    if (file instanceof import_obsidian3.TFile) {
      const content = await app.vault.read(file);
      const parsed = JSON.parse(content);
      if (Array.isArray(parsed)) {
        cachedDreamDb = { dbPath, data: parsed };
        return parsed;
      }
    }
  } catch {
  }
  cachedDreamDb = { dbPath, data: [] };
  return [];
}
async function saveDreamEmbeddingsDatabase(app, settings, data) {
  const dbPath = getDreamEmbeddingsPath(app, settings);
  cachedDreamDb = { dbPath, data };
  const jsonContent = JSON.stringify(data, null, 2);
  const file = app.vault.getAbstractFileByPath(dbPath);
  if (file instanceof import_obsidian3.TFile) {
    await app.vault.modify(file, jsonContent);
  } else {
    await app.vault.create(dbPath, jsonContent);
  }
}
function cosineSimilarity(vecA, vecB) {
  if (!vecA || !vecB || vecA.length === 0 || vecB.length === 0 || vecA.length !== vecB.length) {
    return 0;
  }
  let dotProduct = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] * vecA[i];
    normB += vecB[i] * vecB[i];
  }
  if (normA === 0 || normB === 0) return 0;
  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}
function searchSimilarEntities(targetVector, database, threshold = 0.35, limit = 40) {
  if (!targetVector || database.length === 0) return [];
  const results = [];
  for (const item of database) {
    if (!item.vector || item.vector.length === 0) continue;
    const sim = cosineSimilarity(targetVector, item.vector);
    if (sim >= threshold) {
      results.push({ item, similarity: sim });
    }
  }
  results.sort((a, b) => b.similarity - a.similarity);
  return results.slice(0, limit);
}
async function getSimilarEntitiesContext(app, apiKey, settings, dreamEmbedding) {
  const db = await loadEmbeddingsDatabase(app, settings);
  if (db.length === 0) return "";
  const matches = searchSimilarEntities(
    dreamEmbedding,
    db,
    settings.similarityThreshold,
    settings.similarityLimit
  );
  if (matches.length === 0) return "";
  const lines = matches.map((m) => {
    const aliasesText = m.item.aliases && m.item.aliases.length > 0 ? ` (aliases: ${m.item.aliases.join(", ")})` : "";
    return `- ${m.item.name} [Type: ${m.item.type || "concept"}]${aliasesText}: ${m.item.description || "No description"}`;
  });
  return lines.join("\n");
}
async function updateEntityEmbeddings(app, apiKey, settings, forceRebuildAll = false, specificFilePaths) {
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  const db = forceRebuildAll ? [] : await loadEmbeddingsDatabase(app, settings);
  const dbMap = /* @__PURE__ */ new Map();
  for (const item of db) {
    dbMap.set(item.file, item);
  }
  const allFiles = app.vault.getMarkdownFiles();
  const entityFiles = allFiles.filter((f) => f.path.startsWith(entitiesFolder));
  const targetFiles = specificFilePaths && specificFilePaths.length > 0 ? entityFiles.filter((f) => specificFilePaths.includes(f.path)) : entityFiles;
  const toProcess = [];
  for (const file of targetFiles) {
    const cache = app.metadataCache.getFileCache(file);
    const frontmatterObj = cache?.frontmatter;
    if (!frontmatterObj || frontmatterObj.type !== "entity") continue;
    const entityName = file.basename;
    const entityType = typeof frontmatterObj.entity_type === "string" ? frontmatterObj.entity_type : "concept";
    const aliases = Array.isArray(frontmatterObj.aliases) ? frontmatterObj.aliases.map((x) => String(x)) : [];
    const description = typeof frontmatterObj.description === "string" ? frontmatterObj.description : "";
    const textToEmbed = `${entityName}. ${description}. Aliases: ${aliases.join(", ")}`;
    const existing = dbMap.get(file.path);
    if (!forceRebuildAll && existing && existing.textHash === simpleHash(textToEmbed)) {
      continue;
    }
    toProcess.push({
      file,
      textToEmbed,
      name: entityName,
      type: entityType,
      aliases,
      description
    });
  }
  if (toProcess.length === 0) return 0;
  const BATCH_SIZE = 20;
  let processedCount = 0;
  for (let i = 0; i < toProcess.length; i += BATCH_SIZE) {
    const batch = toProcess.slice(i, i + BATCH_SIZE);
    const inputs = batch.map((b) => b.textToEmbed);
    const embeddings = await getBatchEmbeddings(apiKey, settings.embeddingModel, inputs);
    for (let j = 0; j < batch.length; j++) {
      const item = batch[j];
      const vec = embeddings[j];
      if (!vec) continue;
      const hash = simpleHash(item.textToEmbed);
      const dbItem = {
        id: `entity_${item.file.basename}`,
        file: item.file.path,
        name: item.name,
        type: item.type,
        aliases: item.aliases,
        description: item.description,
        vector: vec,
        textHash: hash
      };
      dbMap.set(item.file.path, dbItem);
      await app.fileManager.processFrontMatter(item.file, (fmFront) => {
        fmFront.embedding_status = "active";
        fmFront.embedding_id = dbItem.id;
      });
      processedCount++;
    }
  }
  const updatedDb = Array.from(dbMap.values());
  await saveEmbeddingsDatabase(app, settings, updatedDb);
  return processedCount;
}
function simpleHash(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0;
  }
  return hash.toString(36);
}
function analyzeDreamConnections(currentDreamFile, currentVector, currentEntities, dreamDatabase, limit = 5) {
  if (dreamDatabase.length === 0) return [];
  const results = [];
  const curEntitySet = new Set(currentEntities.map((e) => e.toLowerCase()));
  for (const dream of dreamDatabase) {
    if (dream.file === currentDreamFile.path || dream.name === currentDreamFile.basename) {
      continue;
    }
    let vectorSim = 0;
    if (currentVector && dream.vector && dream.vector.length > 0) {
      vectorSim = cosineSimilarity(currentVector, dream.vector);
    }
    const otherEntities = (dream.entities || []).map((e) => e.toLowerCase());
    const sharedEntities = [];
    for (const entity of otherEntities) {
      if (curEntitySet.has(entity)) {
        sharedEntities.push(entity);
      }
    }
    const entitySim = (dream.entities || []).length > 0 ? sharedEntities.length / Math.max(curEntitySet.size, dream.entities.length) : 0;
    const combinedScore = vectorSim * 0.5 + entitySim * 0.5;
    if (combinedScore > 0.15 || sharedEntities.length > 0) {
      results.push({
        dreamFile: dream.file,
        dreamName: dream.name,
        date: dream.date || "",
        vectorSimilarity: vectorSim,
        sharedEntities: sharedEntities.map((e) => e.charAt(0).toUpperCase() + e.slice(1)),
        score: combinedScore
      });
    }
  }
  results.sort((a, b) => b.score - a.score);
  return results.slice(0, limit);
}
function formatDreamConnectionsMarkdown(connections) {
  if (connections.length === 0) {
    return "_\u041F\u043E\u043A\u0438 \u0449\u043E \u043D\u0435 \u0437\u043D\u0430\u0439\u0434\u0435\u043D\u043E \u0441\u0445\u043E\u0436\u0438\u0445 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u0445 \u0441\u043D\u0456\u0432._";
  }
  const lines = connections.map((conn) => {
    const percent = Math.round(conn.score * 100);
    const sharedText = conn.sharedEntities.length > 0 ? ` (\u0441\u043F\u0456\u043B\u044C\u043D\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456: ${conn.sharedEntities.map((e) => `[[${e}]]`).join(", ")})` : "";
    const dateText = conn.date ? ` [${conn.date}]` : "";
    return `- [[${conn.dreamName}]]${dateText} \u2014 \u0441\u0445\u043E\u0436\u0456\u0441\u0442\u044C ${percent}%${sharedText}`;
  });
  return lines.join("\n");
}

// src/dreamCreator.ts
var import_obsidian4 = require("obsidian");
function getMoment(date, format) {
  const fn = import_obsidian4.moment;
  return fn(date, format);
}
async function ensureFolder(app, path) {
  const normalizedPath = path.trim().replace(/\/$/, "");
  if (!app.vault.getAbstractFileByPath(normalizedPath)) {
    await app.vault.createFolder(normalizedPath);
  }
}
var DatePickerModal = class extends import_obsidian4.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: t("dateModalTitle") });
    let selectedDate = getMoment().format("YYYY-MM-DD");
    new import_obsidian4.Setting(contentEl).setName(t("dateModalLabel")).addText((text) => {
      text.inputEl.type = "date";
      text.setValue(selectedDate);
      text.onChange((value) => {
        if (value) selectedDate = value;
      });
    });
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText(t("dateModalButton")).setCta().onClick(() => {
      this.close();
      this.onSubmit(selectedDate);
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
async function createDreamNoteForDate(app, settings, targetDateInput) {
  const now = targetDateInput ? getMoment(targetDateInput, ["YYYY-MM-DD", "D.MM.YYYY", "DD.MM.YYYY"]) : getMoment();
  if (!now.isValid()) {
    new import_obsidian4.Notice("\u041D\u0435\u043A\u043E\u0440\u0435\u043A\u0442\u043D\u0438\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 \u0434\u0430\u0442\u0438");
    return;
  }
  const dateStr = now.format("YYYY-MM-DD");
  const dreamsFolder = getDreamsSubfolder(app, settings);
  await ensureFolder(app, dreamsFolder);
  const filePath = `${dreamsFolder}/${dateStr}.md`;
  const existingFile = app.vault.getAbstractFileByPath(filePath);
  if (existingFile instanceof import_obsidian4.TFile) {
    new import_obsidian4.Notice(t("dreamAlreadyExists"));
    const leaf2 = app.workspace.getLeaf(true);
    await leaf2.openFile(existingFile);
    return existingFile;
  }
  const days = tList("days");
  const dayOfWeek = days[now.day()] || "";
  const templateContent = `---
type: dream
date: ${dateStr}
tags:
  - dream
lucid: false
lucidity_level: 0
vividness: 3
sleep_quality: 3
dream_signs: []
emotions: []
characters: []
places: []
objects: []
symbols: []
concepts: []
keywords: []
entities_checked: false
---

# \u0421\u043E\u043D \u0432\u0456\u0434 ${dateStr} (${dayOfWeek})

## \u{1F4DD} \u0417\u0430\u043F\u0438\u0441 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F

> \u0412\u0432\u0435\u0434\u0456\u0442\u044C \u0441\u044E\u0434\u0438 \u0441\u0432\u0456\u0439 \u0442\u0435\u043A\u0441\u0442 \u0441\u043D\u0443...

## \u{1F4CA} \u041C\u0435\u0442\u0430\u0434\u0430\u043D\u0456 \u0442\u0430 \u041E\u0446\u0456\u043D\u043A\u0438

- **\u0422\u0438\u043F \u0441\u043D\u0443**: \u{1F7E5} \u0417\u0432\u0438\u0447\u0430\u0439\u043D\u0438\u0439 / \u{1F7E9} \u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u0439 (\u041E\u0421)
- **\u0420\u0456\u0432\u0435\u043D\u044C \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043E\u0441\u0442\u0456 (0-5)**: 0
- **\u042F\u0441\u043A\u0440\u0430\u0432\u0456\u0441\u0442\u044C (1-5)**: 3
- **\u042F\u043A\u0456\u0441\u0442\u044C \u0441\u043D\u0443 (1-5)**: 3
- **\u041C\u0430\u0440\u043A\u0435\u0440\u0438 \u0441\u043D\u0443 (Dream Signs)**: -

# AI \u0430\u043D\u0430\u043B\u0456\u0437

## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441

-

## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438

-
`;
  const newFile = await app.vault.create(filePath, templateContent);
  new import_obsidian4.Notice(t("dreamCreated"));
  const leaf = app.workspace.getLeaf(true);
  await leaf.openFile(newFile);
  await ensureDreamDashboard(app, settings);
  await ensureEntityIndexes(app, settings);
  return newFile;
}
async function createTodayDreamNote(app, settings) {
  return await createDreamNoteForDate(app, settings);
}
async function ensureDreamDashboard(app, settings) {
  const dreamsBase = settings.dreamsFolder.trim().replace(/\/$/, "") || "Dreams";
  await ensureFolder(app, dreamsBase);
  const ukDashboardPath = `${dreamsBase}/\u0414\u0430\u0448\u0431\u043E\u0440\u0434 \u0441\u043D\u0456\u0432.md`;
  const enDashboardPath = `${dreamsBase}/Dream Dashboard.md`;
  const ukFile = app.vault.getAbstractFileByPath(ukDashboardPath);
  const enFile = app.vault.getAbstractFileByPath(enDashboardPath);
  const targetPath = enFile instanceof import_obsidian4.TFile ? enDashboardPath : ukDashboardPath;
  const existingFile = enFile instanceof import_obsidian4.TFile ? enFile : ukFile instanceof import_obsidian4.TFile ? ukFile : null;
  const dreamsSubfolder = getDreamsSubfolder(app, settings);
  const entitiesSubfolder = getEntitiesSubfolder(app, settings);
  const content = `${t("dashboardTitle")}

${t("dashboardCallout")}

${t("dashboardSectionStats")}

\`\`\`dataview
TABLE WITHOUT ID
length(rows) AS "\u0412\u0441\u044C\u043E\u0433\u043E \u0441\u043D\u0456\u0432",
length(filter(rows, (r) => r.lucid = true)) AS "\u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u0445 (\u041E\u0421)",
round(length(filter(rows, (r) => r.lucid = true)) / length(rows) * 100, 1) + "%" AS "% \u041E\u0421",
round(average(rows.vividness), 1) AS "\u0421\u0435\u0440. \u044F\u0441\u043A\u0440\u0430\u0432\u0456\u0441\u0442\u044C",
round(average(rows.sleep_quality), 1) AS "\u0421\u0435\u0440. \u044F\u043A\u0456\u0441\u0442\u044C \u0441\u043D\u0443"
FROM "${dreamsSubfolder}"
WHERE type = "dream"
\`\`\`

${t("dashboardSectionSigns")}

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u0422\u0440\u0438\u0433\u0435\u0440 / \u041F\u043E\u043D\u044F\u0442\u0442\u044F",
entity_type AS "\u041A\u0430\u0442\u0435\u0433\u043E\u0440\u0456\u044F",
dream_count AS "\u0427\u0430\u0441\u0442\u043E\u0442\u0430 \u0443 \u0441\u043D\u0430\u0445",
last_seen AS "\u041E\u0441\u0442\u0430\u043D\u043D\u044F \u043F\u043E\u044F\u0432\u0430"
FROM "${entitiesSubfolder}"
WHERE type = "entity" AND contains(list("character", "place", "symbol", "object"), entity_type)
SORT dream_count DESC
LIMIT 15
\`\`\`

${t("dashboardSectionEmotions")}

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u0415\u043C\u043E\u0446\u0456\u044F / \u0421\u0442\u0430\u043D",
dream_count AS "\u041F\u043E\u044F\u0432 \u0443 \u0441\u043D\u0430\u0445",
last_seen AS "\u041E\u0441\u0442\u0430\u043D\u043D\u0456\u0439 \u0441\u043E\u043D"
FROM "${entitiesSubfolder}"
WHERE entity_type = "emotion"
SORT dream_count DESC
LIMIT 15
\`\`\`

${t("dashboardSectionCreative")}

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u0406\u0434\u0435\u044F / \u041A\u043E\u043D\u0446\u0435\u043F\u0442",
entity_type AS "\u0422\u0438\u043F",
description AS "\u041E\u043F\u0438\u0441 \u0442\u0430 \u0441\u044E\u0436\u0435\u0442\u043D\u0438\u0439 \u043F\u043E\u0442\u0435\u043D\u0446\u0456\u0430\u043B",
dream_count AS "\u0417\u0433\u0430\u0434\u043E\u043A \u0443 \u0441\u043D\u0430\u0445"
FROM "${entitiesSubfolder}"
WHERE type = "entity" AND contains(list("concept", "character", "place"), entity_type) AND length(description) > 0
SORT dream_count DESC
LIMIT 20
\`\`\`

${t("dashboardSectionLucid")}

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u0421\u043E\u043D",
date AS "\u0414\u0430\u0442\u0430",
lucidity_level AS "\u0420\u0456\u0432\u0435\u043D\u044C \u041E\u0421 (1-5)",
vividness AS "\u042F\u0441\u043A\u0440\u0430\u0432\u0456\u0441\u0442\u044C",
dream_signs AS "\u041C\u0430\u0440\u043A\u0435\u0440\u0438 \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043D\u044F"
FROM "${dreamsSubfolder}"
WHERE type = "dream" AND lucid = true
SORT date DESC
\`\`\`

${t("dashboardSectionRecent")}

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u0421\u043E\u043D",
date AS "\u0414\u0430\u0442\u0430",
choice(lucid, "\u041E\u0421", "\u0417\u0432\u0438\u0447\u0430\u0439\u043D\u0438\u0439") AS "\u0422\u0438\u043F",
vividness AS "\u042F\u0441\u043A\u0440\u0430\u0432\u0456\u0441\u0442\u044C",
characters AS "\u041F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0456",
places AS "\u041B\u043E\u043A\u0430\u0446\u0456\u0457",
concepts AS "\u041A\u043E\u043D\u0446\u0435\u043F\u0442\u0438"
FROM "${dreamsSubfolder}"
WHERE type = "dream"
SORT date DESC
LIMIT 10
\`\`\`
`;
  if (existingFile instanceof import_obsidian4.TFile) {
    await app.vault.modify(existingFile, content);
  } else {
    await app.vault.create(targetPath, content);
  }
}
async function ensureEntityIndexes(app, settings) {
  const baseFolder = getEntitiesSubfolder(app, settings);
  await ensureFolder(app, baseFolder);
  const lang = getLocale();
  const indexFileName = lang === "uk" ? "! \u0406\u043D\u0434\u0435\u043A\u0441.md" : "! Indexes.md";
  for (const type of ENTITY_TYPES) {
    const categoryFolder = `${baseFolder}/${type.folder}`;
    await ensureFolder(app, categoryFolder);
    const indexPath = `${categoryFolder}/${indexFileName}`;
    const existingFile = app.vault.getAbstractFileByPath(indexPath);
    const indexContent = `# \u0406\u043D\u0434\u0435\u043A\u0441: ${type.folder}

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u041D\u0430\u0437\u0432\u0430",
aliases AS "\u0410\u043B\u0456\u0430\u0441\u0438 / \u0421\u0438\u043D\u043E\u043D\u0456\u043C\u0438",
description AS "\u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441",
dream_count AS "\u041F\u043E\u044F\u0432 \u0443 \u0441\u043D\u0430\u0445",
last_seen AS "\u041E\u0441\u0442\u0430\u043D\u043D\u044F \u043F\u043E\u044F\u0432\u0430"
FROM "${categoryFolder}"
WHERE type = "entity" AND file.name != "${indexFileName.replace(".md", "")}"
SORT dream_count DESC
\`\`\`
`;
    if (existingFile instanceof import_obsidian4.TFile) {
      await app.vault.modify(existingFile, indexContent);
    } else {
      await app.vault.create(indexPath, indexContent);
    }
  }
}
async function exportTemplaterTemplate(app, settings) {
  const templatePath = (settings.templateFilePath || "Templates/Dream Template.md").trim().replace(/\/$/, "");
  const parentFolder = templatePath.substring(0, templatePath.lastIndexOf("/"));
  if (parentFolder) {
    await ensureFolder(app, parentFolder);
  }
  const content = `---
type: dream
date: <% tp.file.creation_date("YYYY-MM-DD") %>
tags:
  - dream
lucid: false
lucidity_level: 0
vividness: 3
sleep_quality: 3
dream_signs: []
emotions: []
characters: []
places: []
objects: []
symbols: []
concepts: []
keywords: []
entities_checked: false
---

# \u0421\u043E\u043D \u0432\u0456\u0434 <% tp.file.title %> (<% tp.file.creation_date("dddd") %>)

## \u{1F4DD} \u0417\u0430\u043F\u0438\u0441 \u0441\u043D\u043E\u0432\u0438\u0434\u0456\u043D\u043D\u044F

> \u0412\u0432\u0435\u0434\u0456\u0442\u044C \u0441\u044E\u0434\u0438 \u0441\u0432\u0456\u0439 \u0442\u0435\u043A\u0441\u0442 \u0441\u043D\u0443...

## \u{1F4CA} \u041C\u0435\u0442\u0430\u0434\u0430\u043D\u0456 \u0442\u0430 \u041E\u0446\u0456\u043D\u043A\u0438

- **\u0422\u0438\u043F \u0441\u043D\u0443**: \u{1F7E5} \u0417\u0432\u0438\u0447\u0430\u0439\u043D\u0438\u0439 / \u{1F7E9} \u0423\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u0439 (\u041E\u0421)
- **\u0420\u0456\u0432\u0435\u043D\u044C \u0443\u0441\u0432\u0456\u0434\u043E\u043C\u043B\u0435\u043D\u043E\u0441\u0442\u0456 (0-5)**: 0
- **\u042F\u0441\u043A\u0440\u0430\u0432\u0456\u0441\u0442\u044C (1-5)**: 3
- **\u042F\u043A\u0456\u0441\u0442\u044C \u0441\u043D\u0443 (1-5)**: 3
- **\u041C\u0430\u0440\u043A\u0435\u0440\u0438 \u0441\u043D\u0443 (Dream Signs)**: -

# AI \u0430\u043D\u0430\u043B\u0456\u0437

## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441

-

## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438

-
`;
  const existingFile = app.vault.getAbstractFileByPath(templatePath);
  if (existingFile instanceof import_obsidian4.TFile) {
    await app.vault.modify(existingFile, content);
  } else {
    await app.vault.create(templatePath, content);
  }
  new import_obsidian4.Notice(t("templateExportSuccess", { path: templatePath }));
}

// src/resetManager.ts
var import_obsidian5 = require("obsidian");
var ConfirmResetModal = class extends import_obsidian5.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: t("resetModalTitle") });
    contentEl.createEl("p", { text: t("resetModalDesc") });
    new import_obsidian5.Setting(contentEl).addButton((btn) => {
      btn.setButtonText(t("resetModalConfirmButton"));
      const btnRecord = btn;
      if (typeof btnRecord.setDestructive === "function") {
        btnRecord.setDestructive(true);
      } else if (typeof btnRecord.setWarning === "function") {
        btnRecord.setWarning();
      }
      btn.onClick(() => {
        this.close();
        this.onConfirm();
      });
    }).addButton((btn) => btn.setButtonText(t("resetModalCancelButton")).onClick(() => {
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
async function resetAllDreamData(app, settings) {
  const dreamsFolder = getDreamsSubfolder(app, settings);
  const entitiesFolder = getEntitiesSubfolder(app, settings);
  let entitiesDeleted = 0;
  let dreamsReset = 0;
  const allFiles = app.vault.getMarkdownFiles();
  const entityFiles = allFiles.filter((f) => f.path.startsWith(entitiesFolder));
  for (const file of entityFiles) {
    try {
      await app.fileManager.trashFile(file);
      entitiesDeleted++;
    } catch (e) {
      console.error("Could not trash entity file:", file.path, e);
    }
  }
  const dreamFiles = allFiles.filter((f) => f.path.startsWith(dreamsFolder));
  for (const file of dreamFiles) {
    try {
      await app.fileManager.processFrontMatter(file, (fmRecord) => {
        fmRecord["type"] = "dream";
        fmRecord["entities_checked"] = false;
        fmRecord["characters"] = [];
        fmRecord["places"] = [];
        fmRecord["objects"] = [];
        fmRecord["emotions"] = [];
        fmRecord["symbols"] = [];
        fmRecord["concepts"] = [];
        fmRecord["keywords"] = [];
      });
      let content = await app.vault.read(file);
      if (content.includes("# AI \u0430\u043D\u0430\u043B\u0456\u0437")) {
        content = content.replace(/# AI аналіз[\s\S]*/, "# AI \u0430\u043D\u0430\u043B\u0456\u0437\n\n## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441\n\n\n## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438\n\n-");
        await app.vault.modify(file, content);
      }
      dreamsReset++;
    } catch (e) {
      console.error("Could not reset dream file:", file.path, e);
    }
  }
  await saveEmbeddingsDatabase(app, settings, []);
  await saveDreamEmbeddingsDatabase(app, settings, []);
  return { dreamsReset, entitiesDeleted };
}

// src/suggest.ts
var import_obsidian6 = require("obsidian");
var FolderSuggest = class extends import_obsidian6.AbstractInputSuggest {
  constructor(app, textComponent, onSelectCallback) {
    super(app, textComponent.inputEl);
    this.textComponent = textComponent;
    this.onSelectCallback = onSelectCallback;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerInputStr = (inputStr || "").toLowerCase();
    for (const file of abstractFiles) {
      if (file instanceof import_obsidian6.TFolder) {
        if (!inputStr || file.path.toLowerCase().includes(lowerInputStr)) {
          folders.push(file);
        }
      }
    }
    return folders.slice(0, 50);
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path);
  }
  selectSuggestion(folder, evt) {
    this.textComponent.setValue(folder.path);
    this.onSelectCallback(folder.path);
    this.close();
  }
};
var FileSuggest = class extends import_obsidian6.AbstractInputSuggest {
  constructor(app, textComponent, onSelectCallback) {
    super(app, textComponent.inputEl);
    this.textComponent = textComponent;
    this.onSelectCallback = onSelectCallback;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const files = [];
    const lowerInputStr = (inputStr || "").toLowerCase();
    for (const file of abstractFiles) {
      if (file instanceof import_obsidian6.TFile) {
        if (!inputStr || file.path.toLowerCase().includes(lowerInputStr)) {
          files.push(file);
        }
      }
    }
    return files.slice(0, 50);
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file, evt) {
    this.textComponent.setValue(file.path);
    this.onSelectCallback(file.path);
    this.close();
  }
};

// src/settings.ts
var DreamAnalyzerSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const titleSetting = new import_obsidian7.Setting(containerEl).setName(t("settingsTitle"));
    titleSetting.settingEl.addClass("setting-item-heading");
    const winObj = window;
    const SecretComp = winObj.Obsidian ? winObj.Obsidian.SecretComponent : void 0;
    const appObj = this.app;
    const hasSecretStorage = typeof SecretComp === "function" && typeof appObj["secretStorage"] !== "undefined";
    if (hasSecretStorage && typeof SecretComp === "function") {
      const setting = new import_obsidian7.Setting(containerEl).setName(t("apiKeyName")).setDesc(t("apiKeyDesc"));
      const comp = new SecretComp(this.app, setting.controlEl);
      comp.setValue(this.plugin.settings.openaiApiKey || "");
      comp.onChange((value) => {
        void (async () => {
          this.plugin.settings.openaiApiKey = value ? value.trim() : "";
          await this.plugin.saveSettings();
        })();
      });
    } else {
      new import_obsidian7.Setting(containerEl).setName(t("apiKeyName")).setDesc(t("apiKeyDesc")).addText((text) => {
        text.inputEl.type = "password";
        text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey || "").onChange((value) => {
          void (async () => {
            this.plugin.settings.openaiApiKey = value.trim();
            await this.plugin.saveSettings();
          })();
        });
      });
    }
    new import_obsidian7.Setting(containerEl).setName(t("modelName")).setDesc(t("modelDesc")).addDropdown((dropdown) => dropdown.addOption("gpt-5-mini", t("gptDefaultLabel")).addOption("gpt-4.1-mini", "GPT-4.1 mini").addOption("gpt-5", "GPT-5").addOption("gpt-4o-mini", "GPT-4o mini").addOption("gpt-4o", "GPT-4o").addOption("o3-mini", "o3-mini").setValue(this.plugin.settings.openaiModel || "gpt-5-mini").onChange((value) => {
      void (async () => {
        this.plugin.settings.openaiModel = value;
        await this.plugin.saveSettings();
      })();
    }));
    const journalSection = new import_obsidian7.Setting(containerEl).setName(t("sectionJournalFolder"));
    journalSection.settingEl.addClass("setting-item-heading");
    new import_obsidian7.Setting(containerEl).setName(t("dreamsFolderName")).setDesc(t("dreamsFolderDesc")).addText((text) => {
      const applyFolderChange = async (val) => {
        const cleaned = (0, import_obsidian7.normalizePath)(val.trim());
        if (cleaned) {
          this.plugin.settings.dreamsFolder = cleaned;
          await this.plugin.saveSettings();
          try {
            await ensureEntityIndexes(this.app, this.plugin.settings);
            await ensureDreamDashboard(this.app, this.plugin.settings);
          } catch (e) {
            console.warn("Could not ensure dream dashboard/indexes on folder change:", e);
          }
        }
      };
      new FolderSuggest(this.app, text, (val) => {
        text.setValue(val);
        void applyFolderChange(val);
      });
      text.setPlaceholder("Dreams").setValue(this.plugin.settings.dreamsFolder).onChange((value) => {
        void (async () => {
          this.plugin.settings.dreamsFolder = (0, import_obsidian7.normalizePath)(value.trim());
          await this.plugin.saveSettings();
        })();
      });
      text.inputEl.addEventListener("blur", () => {
        void applyFolderChange(text.getValue());
      });
    });
    const templateExportHeader = new import_obsidian7.Setting(containerEl).setName(t("templateExportName"));
    templateExportHeader.settingEl.addClass("setting-item-heading");
    new import_obsidian7.Setting(containerEl).setName(t("templatePathName")).setDesc(t("templatePathDesc")).addText((text) => {
      new FileSuggest(this.app, text, (val) => {
        void (async () => {
          this.plugin.settings.templateFilePath = (0, import_obsidian7.normalizePath)(val.trim());
          await this.plugin.saveSettings();
        })();
      });
      text.setPlaceholder("Templates/Dream Template.md").setValue(this.plugin.settings.templateFilePath || "Templates/Dream Template.md").onChange((value) => {
        void (async () => {
          this.plugin.settings.templateFilePath = (0, import_obsidian7.normalizePath)(value.trim());
          await this.plugin.saveSettings();
        })();
      });
    });
    new import_obsidian7.Setting(containerEl).setName(t("templateExportName")).setDesc(t("templateExportDesc")).addButton((button) => button.setButtonText(t("templateExportButtonText")).setCta().onClick(() => {
      void (async () => {
        try {
          await exportTemplaterTemplate(this.app, this.plugin.settings);
        } catch (e) {
          const msg = e instanceof Error ? e.message : String(e);
          new import_obsidian7.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0441\u0442\u0432\u043E\u0440\u0435\u043D\u043D\u044F \u0448\u0430\u0431\u043B\u043E\u043D\u0443: " + msg);
        }
      })();
    }));
    const vectorSection = new import_obsidian7.Setting(containerEl).setName(t("sectionVectorSearch"));
    vectorSection.settingEl.addClass("setting-item-heading");
    new import_obsidian7.Setting(containerEl).setName(t("autoEmbeddingsName")).setDesc(t("autoEmbeddingsDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoUpdateEmbeddings).onChange((value) => {
      void (async () => {
        this.plugin.settings.autoUpdateEmbeddings = value;
        await this.plugin.saveSettings();
      })();
    }));
    new import_obsidian7.Setting(containerEl).setName(t("embeddingModelName")).setDesc(t("embeddingModelDesc")).addText((text) => text.setPlaceholder("text-embedding-3-small").setValue(this.plugin.settings.embeddingModel).onChange((value) => {
      void (async () => {
        this.plugin.settings.embeddingModel = value.trim();
        await this.plugin.saveSettings();
      })();
    }));
    new import_obsidian7.Setting(containerEl).setName(t("thresholdName")).setDesc(t("thresholdDesc")).addText((text) => text.setPlaceholder("0.35").setValue(String(this.plugin.settings.similarityThreshold)).onChange((value) => {
      void (async () => {
        const val = parseFloat(value);
        if (!isNaN(val) && val >= 0 && val <= 1) {
          this.plugin.settings.similarityThreshold = val;
          await this.plugin.saveSettings();
        }
      })();
    }));
    new import_obsidian7.Setting(containerEl).setName(t("limitName")).setDesc(t("limitDesc")).addText((text) => text.setPlaceholder("40").setValue(String(this.plugin.settings.similarityLimit)).onChange((value) => {
      void (async () => {
        const val = parseInt(value, 10);
        if (!isNaN(val) && val > 0) {
          this.plugin.settings.similarityLimit = val;
          await this.plugin.saveSettings();
        }
      })();
    }));
    new import_obsidian7.Setting(containerEl).setName(t("rebuildButtonName")).setDesc(t("rebuildButtonDesc")).addButton((button) => button.setButtonText(t("rebuildButtonText")).onClick(() => {
      void (async () => {
        try {
          const apiKey = await getOpenAiApiKey(this.app, this.plugin.settings);
          const notice = new import_obsidian7.Notice(t("rebuildStart"), 0);
          const count = await updateEntityEmbeddings(this.app, apiKey, this.plugin.settings, true);
          notice.hide();
          new import_obsidian7.Notice(t("rebuildSuccess", { count }));
        } catch (e) {
          const msg = e instanceof Error ? e.message : String(e);
          new import_obsidian7.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430: " + msg);
        }
      })();
    }));
    const resetSectionHeader = new import_obsidian7.Setting(containerEl).setName(t("resetSectionTitle"));
    resetSectionHeader.settingEl.addClass("setting-item-heading");
    new import_obsidian7.Setting(containerEl).setName(t("resetSectionTitle")).setDesc(t("resetSectionDesc")).addButton((button) => {
      button.setButtonText(t("resetButtonText"));
      const btnRecord = button;
      if (typeof btnRecord.setDestructive === "function") {
        btnRecord.setDestructive(true);
      } else if (typeof btnRecord.setWarning === "function") {
        btnRecord.setWarning();
      }
      button.onClick(() => {
        new ConfirmResetModal(this.app, () => {
          void (async () => {
            try {
              const notice = new import_obsidian7.Notice("\u041E\u0447\u0438\u0449\u0435\u043D\u043D\u044F \u0434\u0430\u043D\u0438\u0445...", 0);
              const res = await resetAllDreamData(this.app, this.plugin.settings);
              notice.hide();
              new import_obsidian7.Notice(t("resetSuccess", { dreams: res.dreamsReset, entities: res.entitiesDeleted }));
            } catch (e) {
              const msg = e instanceof Error ? e.message : String(e);
              new import_obsidian7.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u043E\u0447\u0438\u0449\u0435\u043D\u043D\u044F: " + msg);
            }
          })();
        }).open();
      });
    });
  }
};

// src/analyzer.ts
var import_obsidian8 = require("obsidian");
function getMoment2() {
  const fn = import_obsidian8.moment;
  return fn();
}
var STOP_ENTITIES_LOWER = /* @__PURE__ */ new Set([
  // Ukrainian
  "\u043E\u043F\u043E\u0432\u0456\u0434\u0430\u0447",
  "\u044F",
  "\u0441\u043D\u043E\u0432\u0438\u0434\u0435\u0446\u044C",
  "\u043C\u043E\u0454 \u0442\u0456\u043B\u043E",
  "\u0432\u043B\u0430\u0441\u043D\u0435 \u0442\u0456\u043B\u043E",
  "\u0441\u0435\u0431\u0435",
  "\u0430\u0432\u0442\u043E\u0440",
  "\u043C\u043E\u044F \u043E\u0441\u043E\u0431\u0430",
  "\u0441\u0430\u043C\u0456\u0441\u0442\u044C",
  // English
  "narrator",
  "i",
  "me",
  "myself",
  "dreamer",
  "my body",
  "self",
  "own body"
]);
function isStopEntity(name) {
  if (!name) return true;
  const lower = name.trim().toLowerCase();
  return STOP_ENTITIES_LOWER.has(lower);
}
var ProgressNotice = class {
  constructor(totalSteps = 5) {
    this.timerId = null;
    this.totalSteps = totalSteps;
    this.step = 1;
    this.currentMessage = "";
    this.startTime = Date.now();
    this.notice = new import_obsidian8.Notice("", 0);
    this.startTimer();
  }
  setStep(step, message) {
    this.step = step;
    this.currentMessage = message;
    this.updateText();
  }
  startTimer() {
    this.timerId = window.setInterval(() => {
      this.updateText();
    }, 1e3);
  }
  updateText() {
    const elapsedSec = Math.floor((Date.now() - this.startTime) / 1e3);
    this.notice.setMessage(`[${this.step}/${this.totalSteps}] ${this.currentMessage} (${elapsedSec}s)`);
  }
  close() {
    if (this.timerId !== null) {
      window.clearInterval(this.timerId);
      this.timerId = null;
    }
    this.notice.hide();
  }
  getElapsedSeconds() {
    return Math.floor((Date.now() - this.startTime) / 1e3);
  }
};
async function analyzeDream(app, file, settings) {
  if (!file) {
    new import_obsidian8.Notice("\u041D\u0435\u043C\u0430\u0454 \u0432\u0456\u0434\u043A\u0440\u0438\u0442\u043E\u0457 \u043D\u043E\u0442\u0430\u0442\u043A\u0438 \u0441\u043D\u0443");
    return;
  }
  let apiKey;
  try {
    apiKey = await getOpenAiApiKey(app, settings);
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    new import_obsidian8.Notice(msg || "\u041F\u043E\u043C\u0438\u043B\u043A\u0430 OpenAI API Key");
    return;
  }
  const progress = new ProgressNotice(5);
  try {
    progress.setStep(1, "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0456\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0434\u0430\u043D\u0438\u0445 \u0441\u043D\u0443...");
    const dreamContent = await app.vault.read(file);
    const dreamEmbedding = await getEmbedding(apiKey, settings.embeddingModel, dreamContent);
    progress.setStep(2, "\u041F\u043E\u0448\u0443\u043A \u0441\u0445\u043E\u0436\u0438\u0445 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439...");
    const similarEntities = await getSimilarEntitiesContext(app, apiKey, settings, dreamEmbedding);
    const entityContext = similarEntities || "No existing similar entities found.";
    progress.setStep(3, `\u0417\u0430\u043F\u0438\u0442 \u0434\u043E OpenAI (${settings.openaiModel})...`);
    const systemPrompt = `
You analyze a personal dream journal for creating a structured Obsidian knowledge base.
Here is a list of existing entities that might match this dream:

${entityContext}

Use existing entities if they fit. Do not create a new entity if an identical or very close entity already exists.

CRITICAL LANGUAGE REQUIREMENT:
- Automatically detect the language of the provided dream text (e.g., Ukrainian, English, etc.).
- ALL returned text fields ("summary", "name", "description", "aliases", "keywords") MUST be in the EXACT SAME LANGUAGE as the dream text.
- Do NOT translate the dream content, entity names, descriptions, or keywords into another language.

STOP ENTITIES & DEDUPLICATION RULES:
- Do NOT create trivial self-referential entities representing the dreamer or narrator (e.g., "Narrator", "Dreamer", "I", "Me", "My body", "Myself", "\u041E\u043F\u043E\u0432\u0456\u0434\u0430\u0447", "\u042F", "\u0421\u043D\u043E\u0432\u0438\u0434\u0435\u0446\u044C", "\u041C\u043E\u0454 \u0442\u0456\u043B\u043E", "\u0412\u043B\u0430\u0441\u043D\u0435 \u0442\u0456\u043B\u043E", "\u0421\u0435\u0431\u0435").
- If the dreamer's identity, body transformation, or state of self is an important plot point, record this via appropriate "concepts" (e.g., "Body Transformation", "Identity Change", "\u0422\u0440\u0430\u043D\u0441\u0444\u043E\u0440\u043C\u0430\u0446\u0456\u044F \u0442\u0456\u043B\u0430", "\u0417\u043C\u0456\u043D\u0430 \u043E\u0441\u043E\u0431\u0438\u0441\u0442\u043E\u0441\u0442\u0456"), NOT via a "Narrator" character entity.
- Each entity must have a SINGLE unique name across all categories. Do NOT return duplicate entity names in different categories (e.g. if an item is an Object "Ladder", do NOT also create a Symbol "Ladder").

Return JSON ONLY.
Format:

{
"summary":"",
"characters":[],
"places":[],
"objects":[],
"emotions":[],
"symbols":[],
"concepts":[],
"keywords":[]
}

CRITICAL FORMAT RULES:
- Do NOT use [[ ]] brackets in JSON values.
- Do NOT invent entities that are not present in the dream text.
- Do NOT add entities just to fill up categories.
- If there is not enough information for a category \u2014 keep the array empty.
- The same entity must maintain a stable name across different dreams.

ENTITY OBJECT FORMAT:
In characters, places, objects, emotions, symbols, concepts arrays, return objects:
{
"name":"",
"description":"",
"aliases":[]
}

name:
Short, stable entity name in the same language as the dream text.

description:
Short factual description of the entity in this specific dream. No psychology or subjective interpretations.

aliases:
Alternative names in the same language. Empty [] if none.

ENTITY NAMING RULES:
- Keep the name short and concise.
- Use one standard form across dreams.
- Ensure names are suitable as Obsidian note titles.
- Do NOT include symbols: / \\ : * ? " < > |

CATEGORIES:
characters: Specific people, creatures, or characters with a role in the dream (EXCLUDING the dreamer/narrator).
places: Independent locations, spaces, or geographic places.
objects: Physical items that exist in the dream as distinct objects.
emotions: Feelings, emotions, or internal mental states.
symbols: Potentially recurring motifs, symbols, or imagery.
concepts: Broad abstract themes, plot events, or transformations.
keywords: 5-15 search keywords in the dream's language.

summary:
A short summary of the dream in 2-5 sentences in the dream's language.
`;
    const rawResult = await requestChatCompletion(
      apiKey,
      settings.openaiModel,
      systemPrompt,
      dreamContent
    );
    const result = {
      summary: typeof rawResult.summary === "string" ? rawResult.summary : "",
      characters: normalizeEntityArray(rawResult.characters),
      places: normalizeEntityArray(rawResult.places),
      objects: normalizeEntityArray(rawResult.objects),
      emotions: normalizeEntityArray(rawResult.emotions),
      symbols: normalizeEntityArray(rawResult.symbols),
      concepts: normalizeEntityArray(rawResult.concepts),
      keywords: normalizeStringArray(rawResult.keywords)
    };
    progress.setStep(4, "\u0421\u0442\u0432\u043E\u0440\u0435\u043D\u043D\u044F \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0435\u0439 \u0442\u0430 \u0440\u043E\u0437\u0440\u0430\u0445\u0443\u043D\u043E\u043A \u0437\u0432'\u044F\u0437\u043A\u0456\u0432...");
    const modifiedEntityPaths = await createOrUpdateEntities(app, result, file, settings);
    const currentEntityNames = [
      ...result.characters,
      ...result.places,
      ...result.objects,
      ...result.symbols,
      ...result.concepts
    ].map((e) => cleanEntityName(e.name)).filter(Boolean);
    const dreamDb = await loadDreamEmbeddingsDatabase(app, settings);
    const connections = analyzeDreamConnections(file, dreamEmbedding, currentEntityNames, dreamDb);
    const connectionsMarkdown = formatDreamConnectionsMarkdown(connections);
    await app.fileManager.processFrontMatter(file, (fm) => {
      fm.type = "dream";
      fm.entities_checked = true;
      const toLinks = (arr) => arr.map((x) => `[[${cleanEntityName(x.name)}]]`);
      fm.characters = toLinks(result.characters);
      fm.places = toLinks(result.places);
      fm.objects = toLinks(result.objects);
      fm.emotions = toLinks(result.emotions);
      fm.symbols = toLinks(result.symbols);
      fm.concepts = toLinks(result.concepts);
      fm.keywords = result.keywords.map((x) => cleanEntityName(x));
    });
    const aiText = `
# AI \u0430\u043D\u0430\u043B\u0456\u0437

## \u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u043E\u043F\u0438\u0441

${result.summary || "-"}

## \u041C\u043E\u0436\u043B\u0438\u0432\u0456 \u0437\u0432'\u044F\u0437\u043A\u0438 \u0437 \u043F\u043E\u043F\u0435\u0440\u0435\u0434\u043D\u0456\u043C\u0438 \u0441\u043D\u0430\u043C\u0438

${connectionsMarkdown}
`;
    let updatedContent = await app.vault.read(file);
    if (updatedContent.includes("# AI \u0430\u043D\u0430\u043B\u0456\u0437")) {
      updatedContent = updatedContent.replace(/# AI аналіз[\s\S]*/, aiText.trim());
    } else {
      updatedContent += `

${aiText.trim()}`;
    }
    await app.vault.modify(file, updatedContent);
    const createdDate = getMoment2().format("YYYY-MM-DD");
    const cache = app.metadataCache.getFileCache(file);
    const frontmatterObj = cache?.frontmatter;
    const dreamDate = typeof frontmatterObj?.date === "string" ? frontmatterObj.date : createdDate;
    const updatedDreamDb = dreamDb.filter((d) => d.file !== file.path && d.name !== file.basename);
    updatedDreamDb.push({
      id: `dream_${file.basename}`,
      file: file.path,
      name: file.basename,
      date: dreamDate,
      entities: currentEntityNames,
      vector: dreamEmbedding
    });
    await saveDreamEmbeddingsDatabase(app, settings, updatedDreamDb);
    if (settings.autoUpdateEmbeddings && modifiedEntityPaths.length > 0) {
      progress.setStep(5, "\u041F\u0430\u043A\u0435\u0442\u043D\u0435 \u043E\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u044F \u0432\u0435\u043A\u0442\u043E\u0440\u043D\u0438\u0445 \u0435\u043C\u0431\u0435\u0434\u0456\u043D\u0433\u0456\u0432...");
      await updateEntityEmbeddings(app, apiKey, settings, false, modifiedEntityPaths);
    }
    const totalSec = progress.getElapsedSeconds();
    progress.close();
    new import_obsidian8.Notice(`\u0421\u043E\u043D \u0443\u0441\u043F\u0456\u0448\u043D\u043E \u043F\u0440\u043E\u0430\u043D\u0430\u043B\u0456\u0437\u043E\u0432\u0430\u043D\u043E \u0437\u0430 ${totalSec}\u0441!`);
  } catch (error) {
    progress.close();
    const msg = error instanceof Error ? error.message : String(error);
    new import_obsidian8.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u0430\u043D\u0430\u043B\u0456\u0437\u0443 \u0441\u043D\u0443: " + msg);
  }
}
function normalizeEntityArray(value) {
  if (!Array.isArray(value)) return [];
  return value.map((item) => {
    if (typeof item === "string") {
      const cleaned = cleanEntityName(item);
      return { name: cleaned, description: "", aliases: [] };
    } else if (typeof item === "object" && item !== null) {
      const obj = item;
      const cleaned = cleanEntityName(obj.name);
      const aliases = Array.isArray(obj.aliases) ? obj.aliases.map((a) => cleanEntityName(a)).filter(Boolean) : [];
      return {
        name: cleaned,
        description: typeof obj.description === "string" ? obj.description : "",
        aliases
      };
    }
    return { name: "", description: "", aliases: [] };
  }).filter((item) => item.name.length > 0 && !isStopEntity(item.name));
}
function normalizeStringArray(value) {
  if (!Array.isArray(value)) return [];
  return value.map((x) => cleanEntityName(x)).filter((x) => x.length > 0 && !isStopEntity(x));
}
function cleanEntityName(item) {
  let name = typeof item === "object" && item !== null ? item.name : item;
  let str = String(name || "").replace(/\[\[/g, "").replace(/\]\]/g, "").replace(/[/\\:*?"<>|]/g, "").replace(/\s+/g, " ").trim();
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1);
}
function findExistingEntityFile(app, baseFolder, safeName) {
  for (const type of ENTITY_TYPES) {
    const categoryFolderPath = `${baseFolder}/${type.folder}`;
    const candidatePath = `${categoryFolderPath}/${safeName}.md`;
    const file = app.vault.getAbstractFileByPath(candidatePath);
    if (file instanceof import_obsidian8.TFile) {
      return file;
    }
  }
  return null;
}
async function createOrUpdateEntities(app, result, dreamFile, settings) {
  const dreamName = dreamFile.basename;
  const createdDate = getMoment2().format("YYYY-MM-DD");
  const cache = app.metadataCache.getFileCache(dreamFile);
  const frontmatterObj = cache?.frontmatter;
  const dreamDate = typeof frontmatterObj?.date === "string" ? frontmatterObj.date : createdDate;
  const baseFolder = getEntitiesSubfolder(app, settings);
  await ensureFolder2(app, baseFolder);
  const modifiedPaths = [];
  for (const type of ENTITY_TYPES) {
    const folderPath = `${baseFolder}/${type.folder}`;
    await ensureFolder2(app, folderPath);
    const items = type.field === "characters" ? result.characters : type.field === "places" ? result.places : type.field === "objects" ? result.objects : type.field === "emotions" ? result.emotions : type.field === "symbols" ? result.symbols : result.concepts;
    for (const item of items) {
      const safeName = cleanEntityName(item.name);
      if (!safeName || isStopEntity(safeName)) continue;
      const existingFile = findExistingEntityFile(app, baseFolder, safeName);
      if (existingFile instanceof import_obsidian8.TFile) {
        await app.fileManager.processFrontMatter(existingFile, (fm) => {
          fm.last_seen = dreamDate;
          fm.embedding_status = "pending";
          const dreamLink = `[[${dreamName}]]`;
          if (!Array.isArray(fm.created_from)) {
            fm.created_from = fm.created_from ? [String(fm.created_from)] : [];
          }
          if (!fm.created_from.includes(dreamLink)) {
            fm.created_from.push(dreamLink);
          }
          fm.dream_count = fm.created_from.length;
          if (item.aliases && item.aliases.length > 0) {
            if (!Array.isArray(fm.aliases)) fm.aliases = fm.aliases ? [String(fm.aliases)] : [];
            for (const alias of item.aliases) {
              const cleanAlias = cleanEntityName(alias);
              if (cleanAlias && !isStopEntity(cleanAlias) && !fm.aliases.includes(cleanAlias)) {
                fm.aliases.push(cleanAlias);
              }
            }
          }
        });
        let entityText = await app.vault.read(existingFile);
        const updatedText = appendDreamAppearance(entityText, dreamName, item.description);
        if (entityText !== updatedText) {
          await app.vault.modify(existingFile, updatedText);
        }
        modifiedPaths.push(existingFile.path);
      } else {
        const path = `${folderPath}/${safeName}.md`;
        const bodyContent = makeEntityBodyContent(
          app,
          safeName,
          item,
          dreamName,
          settings
        );
        const newFile = await app.vault.create(path, bodyContent);
        await app.fileManager.processFrontMatter(newFile, (fm) => {
          fm.type = "entity";
          fm.entity_type = type.entity_type;
          fm.created = createdDate;
          fm.last_seen = dreamDate;
          fm.created_from = [`[[${dreamName}]]`];
          fm.dream_count = 1;
          const cleanAliases = Array.isArray(item.aliases) ? item.aliases.map((x) => cleanEntityName(x)).filter((x) => x.length > 0 && !isStopEntity(x)) : [];
          fm.aliases = cleanAliases;
          fm.tags = [type.entity_type];
          fm.description = item.description || "";
          fm.embedding_status = "pending";
          fm.embedding_id = "";
        });
        modifiedPaths.push(path);
      }
    }
  }
  return modifiedPaths;
}
async function ensureFolder2(app, path) {
  const normalizedPath = path.replace(/\/$/, "");
  if (!app.vault.getAbstractFileByPath(normalizedPath)) {
    await app.vault.createFolder(normalizedPath);
  }
}
function makeEntityBodyContent(app, name, item, dreamName, settings) {
  const dreamsFolder = getDreamsSubfolder(app, settings);
  const entitiesSubfolder = getEntitiesSubfolder(app, settings);
  return `# ${name}

## \u041E\u043F\u0438\u0441


## \u041F\u043E\u044F\u0432\u0438 \u0443 \u0441\u043D\u0430\u0445

- [[${dreamName}]]: ${makeInlineText(item.description || "\u043F\u043E\u044F\u0432\u0430 \u0443 \u0441\u043D\u0456")}

## \u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430

\`\`\`dataview
TABLE WITHOUT ID
dream_count AS "\u041F\u043E\u044F\u0432 \u0443 \u0441\u043D\u0430\u0445",
last_seen AS "\u041E\u0441\u0442\u0430\u043D\u043D\u044F \u043F\u043E\u044F\u0432\u0430"
FROM ""
WHERE file.path = this.file.path
\`\`\`

## \u0421\u043D\u0438

\`\`\`dataview
LIST
FROM "${dreamsFolder}"
WHERE contains(characters, this.file.link)
   OR contains(places, this.file.link)
   OR contains(objects, this.file.link)
   OR contains(emotions, this.file.link)
   OR contains(symbols, this.file.link)
   OR contains(concepts, this.file.link)
SORT file.name DESC
LIMIT 20
\`\`\`

## \u041F\u043E\u0432'\u044F\u0437\u0430\u043D\u0456 \u0441\u0443\u0442\u043D\u043E\u0441\u0442\u0456

\`\`\`dataview
TABLE WITHOUT ID
file.link AS "\u0421\u0443\u0442\u043D\u0456\u0441\u0442\u044C",
entity_type AS "\u0422\u0438\u043F",
length(filter(created_from, (d) => contains(this.created_from, d))) AS "\u0421\u043F\u0456\u043B\u044C\u043D\u0438\u0445 \u0441\u043D\u0456\u0432"
FROM "${entitiesSubfolder}"
WHERE length(filter(created_from, (d) => contains(this.created_from, d))) > 0
AND file.path != this.file.path
SORT length(filter(created_from, (d) => contains(this.created_from, d))) DESC
LIMIT 20
\`\`\`

## \u041D\u043E\u0442\u0430\u0442\u043A\u0438

`;
}
function appendDreamAppearance(text, dreamName, description) {
  const line = `- [[${dreamName}]]: ${makeInlineText(description || "\u043F\u043E\u044F\u0432\u0430 \u0443 \u0441\u043D\u0456")}`;
  const sectionPattern = /## Появи у снах\n([\s\S]*?)(?=\n## |$)/;
  const match = text.match(sectionPattern);
  if (!match) {
    return text.replace(
      /## Статистика/,
      `## \u041F\u043E\u044F\u0432\u0438 \u0443 \u0441\u043D\u0430\u0445

${line}

## \u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430`
    );
  }
  if (match[1].includes(`[[${dreamName}]]`)) {
    return text;
  }
  return text.replace(
    sectionPattern,
    `## \u041F\u043E\u044F\u0432\u0438 \u0443 \u0441\u043D\u0430\u0445
${match[1].trim()}
${line}
`
  );
}
function makeInlineText(text) {
  return String(text || "").replace(/\s+/g, " ").trim();
}

// src/main.ts
var DreamAnalyzerPlugin = class extends import_obsidian9.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("sparkles", t("ribbonAnalyze"), () => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        void analyzeDream(this.app, activeFile, this.settings);
      } else {
        new import_obsidian9.Notice(t("openDreamNoteFirst"));
      }
    });
    this.addRibbonIcon("calendar-plus", t("ribbonCreateDream"), () => {
      void createTodayDreamNote(this.app, this.settings);
    });
    this.addCommand({
      id: "analyze-current-dream",
      name: t("cmdAnalyze"),
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        const dreamsSubfolder = getDreamsSubfolder(this.app, this.settings);
        const isDreamFile = activeFile instanceof import_obsidian9.TFile && activeFile.extension === "md" && activeFile.path.startsWith(dreamsSubfolder);
        if (isDreamFile) {
          if (!checking) {
            void analyzeDream(this.app, activeFile, this.settings);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "create-today-dream-note",
      name: t("cmdCreateDream"),
      callback: () => {
        void createTodayDreamNote(this.app, this.settings);
      }
    });
    this.addCommand({
      id: "create-custom-date-dream-note",
      name: t("cmdCreateCustomDateDream"),
      callback: () => {
        new DatePickerModal(this.app, (selectedDate) => {
          void createDreamNoteForDate(this.app, this.settings, selectedDate);
        }).open();
      }
    });
    this.addCommand({
      id: "rebuild-entity-embeddings",
      name: t("cmdRebuildEmbeddings"),
      callback: () => {
        void (async () => {
          try {
            const apiKey = await getOpenAiApiKey(this.app, this.settings);
            const notice = new import_obsidian9.Notice(t("rebuildStart"), 0);
            const count = await updateEntityEmbeddings(this.app, apiKey, this.settings, true);
            notice.hide();
            new import_obsidian9.Notice(t("rebuildSuccess", { count }));
          } catch (e) {
            const msg = e instanceof Error ? e.message : String(e);
            new import_obsidian9.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430: " + msg);
          }
        })();
      }
    });
    this.addCommand({
      id: "reset-all-data",
      name: t("cmdResetAllData"),
      callback: () => {
        new ConfirmResetModal(this.app, () => {
          void (async () => {
            try {
              const notice = new import_obsidian9.Notice("\u041E\u0447\u0438\u0449\u0435\u043D\u043D\u044F \u0434\u0430\u043D\u0438\u0445...", 0);
              const res = await resetAllDreamData(this.app, this.settings);
              notice.hide();
              new import_obsidian9.Notice(t("resetSuccess", { dreams: res.dreamsReset, entities: res.entitiesDeleted }));
            } catch (e) {
              const msg = e instanceof Error ? e.message : String(e);
              new import_obsidian9.Notice("\u041F\u043E\u043C\u0438\u043B\u043A\u0430 \u043E\u0447\u0438\u0449\u0435\u043D\u043D\u044F: " + msg);
            }
          })();
        }).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        const dreamsSubfolder = getDreamsSubfolder(this.app, this.settings);
        if (file instanceof import_obsidian9.TFile && file.extension === "md" && file.path.startsWith(dreamsSubfolder)) {
          menu.addItem((item) => {
            item.setTitle(t("contextMenuAnalyze")).setIcon("sparkles").onClick(() => {
              void analyzeDream(this.app, file, this.settings);
            });
          });
        }
      })
    );
    this.addSettingTab(new DreamAnalyzerSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const rawData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, rawData || {});
    clearMemoryCache();
  }
  async saveSettings() {
    await this.saveData(this.settings);
    clearMemoryCache();
  }
};
